### ISSUE TITLE
firstboot support on read-only root file systems

### ISSUE THREAD

**Issue by laenion** [coreos/ignition#1049]
From what I understand the current approach for firstboot detection is
* Check whether file _/boot/ignition.firstboot_ exists
* Check whether command line parameter `ignition.firstboot` exists (will always enforce firstboot)

The first option however does not work if the root file system including _/boot_ is a read-only file system (as it is the case on openSUSE Kubic systems) - the file cannot be deleted any more.

One option I was thinking about is to additionally use a GRUB2 environment variable instead, e.g. storing something like `ignition.firstboot=1` if the system is supposed to execute Ignition (or the other way around: skip execution if `ignition.firstboot=0`).

Any thoughts on this approach?

**Comment by laenion** [comment]
To answer the last question (sorry for the late reply): No it doesn't. But _02_ignition_firstboot_ has been moved to https://github.com/coreos/fedora-coreos-config anyway, so the implementation is distribution specific now for quite some time.

From my point of view this ticket could be closed, except when you want to keep it open to find a more general approach in the future.

**Comment by jlebon** [comment]
Yeah, the `/boot/ignition.firstboot` mechanism now purely lives at the distro integration layer. Other distros can implement their own mechanism in its place (including just hardcoding the karg and removing it from the boot config if that makes the most sense).

Tentatively closing.

**Comment by jlebon** [comment]
> (including just hardcoding the karg and removing it from the boot config if that makes the most sense).

Which... actually is something we could easily switch to for CoreOS now since we always modify kargs anyway for the rootmap stuff and `rdcore` makes it safe and trivial to do. But meh, probably not worth the churn if there are no additional benefits.
