### ISSUE TITLE
networking and /boot/ignition/config.ign

### ISSUE THREAD

**Issue by cgwalters** [coreos/ignition#1052]
Currently we support dropping `/boot/ignition/config.ign` in the disk image.  This is [used by the coreos-installer](https://github.com/coreos/coreos-installer/blob/fb133d87fcde09fc48a7fa9a42baddf2860ec110/coreos-installer#L355), and in general is a convenient tool for bare metal.

The problem today is that if this file is present, we still require initramfs networking.  I'd like to support a pattern where an entire config can be injected there (without using any includes).

It feels like to generalize this we'd really need Ignition itself to activate networking only when it needs to.

In the mean time...the workaround for this case of "static Ignition with no networking" looks like writing
`set ignition_network_kcmdline=""` in `/boot/ignition.firstboot`
per [this code](https://github.com/coreos/ignition-dracut/blob/8551bc7fd89a80200d94d009ad3d17131fc11dcf/grub/02_ignition_firstboot#L20).

**Comment by arithx** [comment]
Closing as this seems to have been fixed in https://github.com/coreos/fedora-coreos-config/pull/426
