### ISSUE TITLE
fetch-offline fails to request networking on OpenStack/CloudStack

### ISSUE THREAD

**Issue by ITD27M01** [coreos/ignition#1056]
Hi Guys.

We have tested the latest stable image for Fedora CoreOS and it doesnt work in OpenStack environment:

```
[    7.313479] ignition[453]: Ignition 2.4.1
[    7.314417] ignition[453]: Stage: fetch-offline
[    7.315272] ignition[453]: fetched base config from "system"
[    7.316282] ignition[453]: reading system config file "/usr/lib/ignition/base.ign"
[    7.317708] ignition[453]: no config URL provided
[    7.318549] ignition[453]: reading system config file "/usr/lib/ignition/user.ign"
[    7.319952] ignition[453]: no config at "/usr/lib/ignition/user.ign"
[    7.321025] ignition[453]: failed to fetch config from metadata service: resource requires networking
```

The previous stable image (fedora-coreos-32.20200629.3.0-openstack.x86_64) works as expected:
```
[    3.967735] ignition[476]: Ignition 2.3.0
[    3.968525] ignition[476]: Stage: fetch
[    3.969289] ignition[476]: reading system config file "/usr/lib/ignition/base.ign"
[    3.970674] ignition[476]: fetched base config from "system"
[    3.971780] ignition[476]: no config URL provided
[    3.972687] ignition[476]: reading system config file "/usr/lib/ignition/user.ign"
[    3.973940] ignition[476]: no config at "/usr/lib/ignition/user.ign"
[    3.974939] ignition[476]: GET http://169.254.169.254/openstack/latest/user_data: attempt coreos/fedora-coreos-tracker#1
[    3.976381] ignition[476]: GET error: Get "http://169.254.169.254/openstack/latest/user_data": dial tcp 169.254.169.254:80: connect: network is unreachable
[    3.993455] NetworkManager[488]: <info>  [1596191217.7973] NetworkManager (version 1.22.14-1.fc32) is starting... (for the first time)
[    3.995687] NetworkManager[488]: <info>  [1596191217.7999] Read config: /etc/NetworkManager/NetworkManager.conf
[    3.999640] NetworkManager[488]: <info>  [1596191217.8039] auth[0x560eee410450]: create auth-manager: D-Bus connection not available. Polkit is disabled and only root will be authorized.
[    4.003409] NetworkManager[488]: <info>  [1596191217.8076] manager[0x560eee417090]: monitoring kernel firmware directory '/lib/firmware'.
[    4.005550] NetworkManager[488]: <info>  [1596191217.8098] hostname: hostname: hostnamed not used as proxy creation failed with: Could not connect: No such file or directory
<...> and after NetworkManager gets DHCP addresses the ignition gets the user_data
```

The full boot log for new stable image: https://gist.github.com/ITD27M01/2e99e2d62d308d3402de98ed85bd0811

**Comment by ITD27M01** [comment]
Does it mean that OKD 4.5 cannot be deployed on Openstack?

**Comment by jlebon** [comment]
Opened https://github.com/coreos/ignition/pull/1057.

> Does it mean that OKD 4.5 cannot be deployed on Openstack?

Hmm, I think you should be able to use the previous stable release instead and let the cluster auto-update to the latest release.

**Comment by ITD27M01** [comment]
Based on my experiences in the case of IPI, the installer selects image by self.

**Comment by ITD27M01** [comment]
I am also very confused by the heuristic choice of timeout for waiting for the network. I would like to suggest making an explicit dependency of one on the other (ignition on network-online, or other service). Environments can be different and with different loads. And what works in devstack may not work in real installations.

**Comment by bgilbert** [comment]
> I am also very confused by the heuristic choice of timeout for waiting for the network. I would like to suggest making an explicit dependency of one on the other (ignition on network-online, or other service).

If I'm understanding you correctly, that's not really related to this bug, but in general there is no systemd service or target which guarantees the network is up.  It's not even 100% clear, programmatically, what it means for the network to be up.  For example, we may have a route to the Internet, but not yet to a host on another NIC that we need for fetching resources.  So the best we can do is retry requests until they succeed.

**Comment by ITD27M01** [comment]
Hello, 
Yes, it doesn't related to this bug, thank you for explanation.

**Comment by ITD27M01** [comment]
@lucab @bgilbert @jlebon 
Hi Guys. Is there any way to backport this to 2.4 ? Because current fcos images are unusable on OpenStack/RHOSP.

**Comment by lucab** [comment]
In general we try to stick to a flow which is light on backports/branches.
For this specific issue, the last FCOS release in the `testing` stream (`32.20200809.2.1`) contains a fixed Ignition.

**Comment by ITD27M01** [comment]
Thank you for your explanation and fast fix, it sounds good for us.

**Comment by nashford77** [comment]
I have the same issue - has this been fixed and does the V35 testing stream have a working ignition ?

**Comment by bgilbert** [comment]
@nashford77 Yes, this was fixed.  Please open a new bug with details, including a console log and a (redacted) Ignition config.
