### ISSUE TITLE
Automatically build and push quay.io/coreos/ignition-validate container

### ISSUE THREAD

**Issue by edwardxia** [coreos/ignition#1059]
# Feature Request #

Currently, `quay.io/coreos/ignition-validate`'s latest tag is outdated (8 month old).

Specifically, we should automatically build and push `quay.io/coreos/ignition-validate` container and use a similar tagging schema like `quay.io/coreos/fcct`:
  - `master` is built automatically when master is pushed. `latest` is tagged as an alias of `master`.
  - `vX.Y.Z` is built when a release is tagged. `release` is tagged as an alias of latest release.

Once this is in place, maybe also update the README to use `quay.io/coreos/ignition-validate:release`.

**Comment by bgilbert** [comment]
Code changes in https://github.com/coreos/ignition/pull/1063.

**Comment by bgilbert** [comment]
#1063 landed, and I've added a `release` tag in the Quay repo, so this is done.  Thanks for reporting!
