### ISSUE TITLE
AWS user data read as empty

### ISSUE THREAD

**Issue by jimpo** [coreos/ignition#1061]
# Bug #

The ignition config passed to an AWS instance as user data is not getting read correctly.

## Operating System Version ##

AWS EC2 AMI ami-01e7e4463124aaa70

## Ignition Version ##

Whatever ships with FCOS 32.20200715.3.0

## Environment ##

What hardware/cloud provider/hypervisor is being used to run Ignition?

AWS EC2, t3.medium instance.

## Expected Behavior ##

On an AMI built from Fedora CoreOS, the Ignition config passed as user data is not fetched correctly from the instance metadata address. The config is read as empty and therefore not executed.

## Actual Behavior ##

The config should get read and executed.

## Reproduction Steps ##

  1. Launch an EC2 instance with AMI ami-01e7e4463124aaa70. In my testing, I used a t3.micro size. No user data, no SSH key, as basic as possible.
  2. Once the instance is running, create a new AMI from it. This is possible through the AWS console or API.
  3. Launch a new instance with this custom AMI and an ignition config as the user data.
  4. SSH into the machine and notice that the config did not run.
  5. Run `journalctl --identifier ignition --all`. I see the following lines:

    Aug 06 21:45:37 ip-10-0-0-174 ignition[443]: GET http://169.254.169.254/2019-10-01/user-data: attempt #1       
    Aug 06 21:45:37 ip-10-0-0-174 ignition[443]: GET error: Get "http://169.254.169.254/2019-10-01/user-data": dial tcp 169.254.169.254:80: connect: network is unreachable                                            
    Aug 06 21:45:37 ip-10-0-0-174 ignition[443]: GET http://169.254.169.254/2019-10-01/user-data: attempt #2                       
    Aug 06 21:45:37 ip-10-0-0-174 ignition[443]: GET error: Get "http://169.254.169.254/2019-10-01/user-data": dial tcp 
    169.254.169.254:80: connect: network is unreachable                                            
    Aug 06 21:45:38 ip-10-0-0-174 ignition[443]: GET http://169.254.169.254/2019-10-01/user-data: attempt #3                       
    Aug 06 21:45:38 ip-10-0-0-174 ignition[443]: GET result: Not Found                                     
    Aug 06 21:45:38 ip-10-0-0-174 ignition[443]: parsing config with SHA512: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
    Aug 06 21:45:38 ip-10-0-0-174 ignition[443]: not a config (empty): provider config was empty, continuing with empty cache config
    Aug 06 21:45:38 ip-10-0-0-174 ignition[443]: fetch: fetch complete
    Aug 06 21:45:38 ip-10-0-0-174 ignition[443]: fetch: fetch passed

  6. Then run `curl http://169.254.169.254/2019-10-01/user-data | sha512sum`. The output should NOT be `cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e` -- that is the SHA512 hash of an empty string, also evidenced by the following log line `not a config (empty)`.

If you do the same thing using the original FCOS AMI and not the custom built from an instance, the ignition config is loaded correctly, as expected.

**Comment by bgilbert** [comment]
You're seeing old logs from the first boot in step 1.  Ignition only ever runs once in the lifetime of a system, so your workflow in step 2 creates an image which will never run Ignition.

**Comment by jimpo** [comment]
Is there any way to clear that and make Ignition run again if I'm trying to build a new image?

**Comment by bgilbert** [comment]
There's a hack, but we don't recommend it.  Your repurposed image will have the same machine ID, same disk GUID, old logs, etc., unless you're careful to clear all of that out.  What are you trying to accomplish with the double launch?

**Comment by jimpo** [comment]
I'm trying to use the [Packer aws-ebs builder](https://www.packer.io/docs/builders/amazon-ebs) to preinstall some stuff, like docker-compose. I was trying to install and configure a pam module for SSH as well, but I don't need to anymore. So I might just skip this step if it's really a hassle, and loading configuration from user data is a necessity.

**Comment by jimpo** [comment]
Also, I was able to do this on CoreOS using cloud-config and I'm trying to migrate to the newer stuff.

**Comment by bgilbert** [comment]
I'd recommend just including all of your configuration in your Ignition config.  If you're configuring multiple types of machines that share some common config elements, you can use the `ignition.config.merge` directive to put the common elements in a separate config and merge it into your machine-specific configs at runtime.

> Also, I was able to do this on CoreOS using cloud-config and I'm trying to migrate to the newer stuff.

Yup, coreos-cloudinit ran multiple times with multiple data sources and it could be hard to determine the resulting config.  Ignition was designed to avoid that.

**Comment by jimpo** [comment]
Thanks!

**Comment by ziyuanchen-db** [comment]
Seeing this issue too. Does this mean if we're using ignition then we cannot build any custom AMIs? I imagine this would block 90% of use cases. We need to build custom AMIs to install our required stuff as well as some configurations. It's not possible to install all of them during the actual boot with an ignition config that fetches from a source on the internet.
