### ISSUE TITLE
Support multi part mime for user-data for cluster-api

### ISSUE THREAD

**Issue by dongsupark** [coreos/ignition#1072]
# Feature Request #

It would be nice if we could support multi part for user-data, especially for [cluster-api](https://github.com/kubernetes-sigs/cluster-api/).

The ultimate goal would be to support Flatcar Container Linux or Fedora CoreOS in cluster-api. At the moment, however, cluster-api supports only a single bootstrap kubeadm provider, based on cloud-init. It is not possible to bootstrap via ignition. There is a pending [PR](https://github.com/kubernetes-sigs/cluster-api/pull/3437) to add the ignition-based bootstrap provider in cluster-api.

One blocker is, however, that there are corner cases where some infrastructure providers simply assume that cloud-init is available. [AWS provider](https://github.com/kubernetes-sigs/cluster-api-provider-aws/) is one of the examples. It simply makes use of AWS secrets manager, and requires cloud-init to do that. According to @randomvariable , its reason was to prevent users with EC2 read only access from getting the private cert authority information. By making it accessible only the EC2 instance profile via secrets manager, that mode of attack could go away. See https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1387 or https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1875 for details.

One of the solutions would be to make ignition support multi-part mime user-data. In the past there was already an [attempt](https://github.com/coreos/ignition/issues/849) to do that, but the corresponding [PR](https://github.com/coreos/ignition/pull/862) was never merged. At that time, it was resolved instead on the Openstack side.

So question is, would it be a good idea to bring the multi-part mime feature to ignition?
Or is it still a bad idea?

**Comment by bgilbert** [comment]
The concerns raised in #849 still apply.  In general I'm not sure this is something we'd want to support, but a lot depends on the details.  Could you spell out how multi-part support would solve this problem?  Under what circumstances would multipart be used, on what platforms, and what would be the various parts in the multipart envelope?

**Comment by dongsupark** [comment]
> Could you spell out how multi-part support would solve this problem? 

As mentioned above, to avoid storing user-sensitive data into userdata, cluster-api-aws-provider does the following steps:

* split userdata into multiple chunks at 10KB
* uploads the chunks into AWS secrets manager.
  * Its prefix is like `aws.cluster.x-k8s.io/01234567-8901-2345-6789-0123456789`, and each chunk is named incrementally, like `aws.cluster.x-k8s.io/01234567-8901-2345-6789-0123456789-01`, `-02`, etc.
* Compose a multipart MIME message, in order to fetch the uploaded data from the AWS secrets manager.
  * The first part is a pre-defined bash script that fetches secrets to store into `/etc/secret-userdata.txt`.
  * The second part is to simply include the file `/etc/secret-userdata.txt`.

A short example of the multipart MIME message:

```
Content-Type: multipart/mixed; boundary="7cc194c95b686cb8cd0d6ea9c3f6fa39f536324b4e0b333d8deffb59e355"

--7cc194c95b686cb8cd0d6ea9c3f6fa39f536324b4e0b333d8deffb59e355
content-type: text/cloud-boothook

# bash script that fetches secrets to store into /etc/secret-userdata.txt

--7cc194c95b686cb8cd0d6ea9c3f6fa39f536324b4e0b333d8deffb59e355
content-type: text/x-include-url

file:///etc/secret-userdata.txt

--7cc194c95b686cb8cd0d6ea9c3f6fa39f536324b4e0b333d8deffb59e355--
```

(See https://gist.github.com/dongsupark/75eb0fb63a32eab3bffdc884d72165f6 for its full example)

You can see the embedded bash script [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/v0.5.5/pkg/cloud/services/secretsmanager/secret_fetch_script.go), and the actual multipart MIME code [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/v0.5.5/pkg/cloud/services/secretsmanager/cloudinit.go).

I know, it might look complicated to some folks.
Anyway I am just trying to explain how it is.

> what platforms

For now it is only about AWS.
Though I am not completely sure if other infrastructure providers do such cloud-init-specific things as well.

**Comment by randomvariable** [comment]
Cluster API Provider vSphere injects cloud-init networking data via GuestInfo as well, so will need to check for parity with Ignition there as well.

**Comment by bgilbert** [comment]
Okay, thanks for the explanation.  It sounds like the proposal isn't about multi-part MIME support _per se_, but rather that Ignition should:

1. Read `multipart/mixed` userdata from AWS,
2. Execute a bash script in the `text/cloud-boothook` part, inside the initramfs,
3. Read a file URL from the `text/x-include-url` part and use that to read a local file from within the initramfs,
4. Use that file as the Ignition config.

Is that correct?

If so, I don't think that's something we'd want to support.  So far, we've treated the contents of the initramfs as an implementation detail, and haven't supported writing user-specified files there nor running any user code.  To support the shell script, we'd need to add to the initramfs any commands that might conceivably be run from the `cloud-boothook`.  And the general idea of running user-supplied shell scripts isn't really aligned with the declarative model Ignition is designed to enable.

Note that Ignition already has a `merge` mechanism for referencing a subsidiary config at an external URL, including an S3 URL accessed via instance profile credentials.  It seems like it'd be cleaner to store secrets in an authenticated S3 object, and then make the Ignition config in userdata a stub that just points to S3.

**Comment by bgilbert** [comment]
I'll go ahead and close this.  Feel free to post any followups here; we can always reopen if needed.
