### ISSUE TITLE
Ignition fails to mount files from AWS S3 - appears to run before AWS metadata is available (in /run/metadata/flatcar?)

### ISSUE THREAD

**Issue by dwwarr** [coreos/ignition#1076]
# Bug #
I'm trying to run Flatcar Linux in AWS GovCloud.  I created an AMI from the VMDK image. If I use Flatcar Linux 2079 (Ignition 0.31.0), I can launch instances whose user data is Ignition config that mounts files from a private S3 bucket or interacts with AWS in other ways. 

If I use any version of Flatcar Linux after 2079, I cannot.  AWS shows that the instance started, but I cannot ssh into the instance, the system run log appears to show that Ignition tried to pull files from S3 before appropriate AWS metadata was available.  I have no problem launching an instance based on Flatcar Linux > 2079 (Ignition >= 0.32.0) if Ignition does not need to interact with AWS.  But if Ignition needs to interact with AWS, no luck. 

Flatcar Linux 2079 uses Ignition 0.31.0.  Subsequent versions use 0.32.0 or later.  So this problem appears to happen in 0.32.0 or later.  Or I'm doing something wrong that I'm unaware of (completely possible).

I have attached the system log and Ignition config for a trial I did using Flatcar Linux 2512.2.1 Stable (Ignition v0.34.0-18-gfb5031b).  The logs show this error when trying to pull the files from S3:
```
dial tcp: lookup s3.amazonaws.com on [::1]:53: dial udp [::1]:53: connect: cannot assign requested address
```

If Ignition had the proper AWS metadata, it would be looking for s3-us-gov-west-1.amazonaws.com, I believe.  Also, the DNS names for s3.amazonaws.com and s3-us-gov-west-1.amazonaws.com would resolve.

## Operating System Version ##
Any version after 2079.6.0 stable.  Attached log is for 2512.2.1.

## Ignition Version ##
0.32.0 or later.  Attached log is for v0.34.0-18-gfb5031b

## Environment ##
AWS GovCloud (us-gov-west-1).  I created the AMIs from the stable VMDK images.

What hardware/cloud provider/hypervisor is being used to run Ignition?

## Expected Behavior ##

Ignition runs successfully, creating files on the disk whose contents are pulled from S3.  This works in 2079.6.0 stable.

## Actual Behavior ##

Ignition fails - system logs appear to indicate that Ignition tried to run before AWS metadata (which appears to me to be in /run/metadata/flatcar) is available.  Sample logs attached.
Cannot ssh into the instance when this occurs.  When you try to, you get this error:
`ssh_exchange_identification: Connection closed by remote host`

## Reproduction Steps ##

  1. Use an AMI based on any Flatcar Linux version after 2079.6.0
[flatcar_linux_2512.3.0_system_log.txt](https://github.com/coreos/ignition/files/5119912/flatcar_linux_2512.3.0_system_log.txt)
[flatcar_linux_2512_ignition.txt](https://github.com/coreos/ignition/files/5119918/flatcar_linux_2512_ignition.txt)

  2. Set user-data to be an Ignition script that mounts files from non-public locations in S3.  The instance's IAM role is supposed to grant it access to the S3 bucket.

  3. Try to start an instance.  AWS will shows that the instance started, but you cannot ssh into it.

**Comment by bgilbert** [comment]
Are you able to reproduce this with Ignition 2.x, e.g. on Fedora CoreOS?  Ignition 0.x is no longer maintained upstream.

**Comment by dwwarr** [comment]
Yes.  The system logs show completely different stuff, but the result is the same.

I created a Fedora CoreOS AMI based on their VMDK image for 32.20200726.3.1, which uses Ignition 2.4.1.
I can start the instance fine if Ignition doesn't need to interact with AWS, but if it does, the result is that I cannot ssh into the server.  When I try I get this error: `ssh_exchange_identification: Connection closed by remote host`.

System logs are attached for the first boot and for the auto reboot that happened a couple of minutes later.  The ignition config is the same I attached above.

I can't discern what the problem is from the system logs.  I don't see anything in there complaining about being unable to get stuff from AWS.  But the same issue must be happening since the result is the same.

[Fedora_CoreOS_32.20200726.3.1_system_log.txt](https://github.com/coreos/ignition/files/5120001/Fedora_CoreOS_32.20200726.3.1_system_log.txt)
[Fedora_CoreOS_32.20200726.3.1_system_log_reboot.txt](https://github.com/coreos/ignition/files/5120012/Fedora_CoreOS_32.20200726.3.1_system_log_reboot.txt)

**Comment by bgilbert** [comment]
The error from the FCOS logs is a syntax error in your config:

```
[    9.719728] ignition[468]: error at line 2 col 16: invalid character ':' after top-level value
[    9.790847] ignition[468]: failed to fetch config: config is not valid
```

**Comment by dwwarr** [comment]
Duh, sorry.  I should have used a proper ignition file for Fedora CoreOS.  So ran an EC2 instance based on Fedora CoreOS  32.20200726.3.1 (Ignition 2.4.1), using the attached Ignition config file (which was generated using the FCCT tool).  I see the same result.  AWS says the server starts, but when I try to ssh into it, I get `ssh_exchange_identification: Connection closed by remote host`.  And I can't discern the cause from the system logs, which are attached.

[fcos_ignition.txt](https://github.com/coreos/ignition/files/5120312/fcos_ignition.txt)
[Fedora_CoreOS_32.20200726.3.1_system_log.txt](https://github.com/coreos/ignition/files/5120313/Fedora_CoreOS_32.20200726.3.1_system_log.txt)

**Comment by dwwarr** [comment]
Duh, sorry. I should have used a proper ignition file for Fedora CoreOS. So ran an EC2 instance based on Fedora CoreOS 32.20200726.3.1 (Ignition 2.4.1), using the attached Ignition config file (which was generated using the FCCT tool). I see a similar result. The system log shows this error:
```
[    8.693170] ignition[564]: CRITICAL : files: createFilesystemsFiles: createFiles: op(2): Error fetching file "/sysroot/etc/kubernetes/cloud.conf": couldn't determine the region for bucket "kubeadm20191125162724372200000001": NotFound: Not Found
```
So it appears that Ignition is running before AWS metadata exists, and therefore it can't find the AWS region.

AWS says the server starts, but when I try to ssh into it, I get `ssh_exchange_identification: Connection closed by remote host`.

System logs and ignition config are attached.

[fcos_ignition.txt](https://github.com/coreos/ignition/files/5120387/fcos_ignition.txt)
[Fedora_CoreOS_32.20200726.3.1_system_log.txt](https://github.com/coreos/ignition/files/5120388/Fedora_CoreOS_32.20200726.3.1_system_log.txt)

**Comment by arithx** [comment]
Ok, so I think I've figured out where this could be running into errors with the current code (although I'm still not sure why it was working in `v0.31.0`). The error is being emitted from the [`GetBucketRegion` call](https://github.com/coreos/ignition/blob/master/internal/resource/url.go#L409-L415); we're passing a `regionHint` of `us-east-1` in pretty much all cases with the current code (more on why in a bit) and that [according to the AWS docs](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3manager/#GetBucketRegion) that will fail with a `NotFound` error if the bucket does not exist in the AWS partition the regionHint belongs to.

I think there are two things that need to be fixed here:
1. On the AWS platform we need to properly set the `S3RegionHint` on the `resource.Fetcher` object during all stages of Ignition (currently we're only setting that after we [fetch the config during a `fetch*` stage](https://github.com/coreos/ignition/commit/877735ca4210ac2f7fbb1dca96378dbbfe3141c4)). We should be able to assume that we'll have working networking in non `fetch*` stages so we won't run into the main issue that commit was aimed at fixing if we just run it during the creation of the `resource.Fetcher` object.
2. For non-AWS platforms we'll probably need to attempt the `GetBucketRegion` call with one `regionHint` from each partition.

**Comment by arithx** [comment]
@dwwarr If possible can you test with a custom build containing #1078?

AMI (us-east-1): `ami-08e8eff57f10cb3c5`
AWS VMDK: https://slowrie-fcos.s3.amazonaws.com/ignition-regionhint/32.20200828.dev.0/x86_64/fedora-coreos-32.20200828.dev.0-aws.x86_64.vmdk

**Comment by dwwarr** [comment]
@arithx - Thank you very much for the quick fix (or at least an attempt at one)! I will try with the VMDK you mention on Monday.

**Comment by dwwarr** [comment]
@arithx - Thank you!  Your fix works for me.  Using your VMDK image and the user data in fcos_ignition.txt in my last comment on 24 Aug, I am able to successfully run an EC2 instance in AWS GovCloud (us-gov-west-1) which mounts files from S3.

**Comment by arithx** [comment]
Closing as #1078 has merged.
