### ISSUE TITLE
Support for RAM-disk deployments

### ISSUE THREAD

**Issue by crawford** [coreos/ignition#109]
If there is no disk, ignition won't run. There should be an alternative trigger (maybe a kernel parameter).

**Comment by vcaputo** [comment]
kernel parameter for forcing ignition sounds reasonable to me.

**Comment by vcaputo** [comment]
Leaning towards the use of a `coreos.ignition` kernel parameter to force ignition to run.  It's too bad there isn't an `rd.systemd.wants=` analogous to `systemd.wants=` we could use for forcing `ignition-disks.service`.

**Comment by crawford** [comment]
https://github.com/coreos/bootengine/pull/58

**Comment by crawford** [comment]
OK, now that that's been merged, `coreos.ignition.force=1` will cause Ignition to run.
