### ISSUE TITLE
vmware: kernel_lockdown breaks guestinfo fetching

### ISSUE THREAD

**Issue by lucab** [coreos/ignition#1092]
## Operating System Version ##

RHCOS 4.6 nightly (likely recent FCOS too, haven't directly checked) 

## Ignition Version ##

2.6.0 

## Environment ##

VMware vSphere 7.0, **with EFI and Secure Boot enabled**.

## Reproduction Steps ##

  1. Before booting a VM for the first boot, follow https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-898217D4-689D-4EB5-866C-888353FE241C.html

## Actual Behavior ##

Enabling Secure Boot turns on [kernel_lockdown](https://www.mankier.com/7/kernel_lockdown), which in turn blocks the `iopl` call. Ignition performs that in order to get access to the I/O ports for hypervisor backdoor.

Symptoms are:
 * fetch stages failing with `operation not permitted`
 * kernel logging `Lockdown: iopl is restricted` on the console

Here below is a screenshot from the emergency console.

![ignition-vmware-eperm](https://user-images.githubusercontent.com/98086/92928048-179c1780-f42e-11ea-9c98-f016a9129628.png)

Ref:
 * https://bugzilla.redhat.com/show_bug.cgi?id=1877995
 * https://github.com/lucab/vmw_backdoor-rs/issues/6

**Comment by lucab** [comment]
For reference, this used to work on v0.x releases due to a lucky mess, possibly in a non-deterministic way. This only affects v2.x releases, starting with v2.0.0-beta.

On 0.35.0 Ignition is using an ancient incomplete and forked version of the vmware library: https://github.com/coreos/ignition/tree/v0.35.0/vendor/github.com/sigma. This version does not perform any `iopl` to properly set access right to IO ports.
This theoretically may result in non-deterministic failures depending on I/O port choice (which is picked on each backdoor access by the hypervisor), although I wasn't able to practically encounter them after a dozen of manual attempts.

The library was updated in https://github.com/coreos/ignition/pull/793. It now performs an `iopl` in its initialization path: https://github.com/coreos/ignition/blob/v2.6.0/vendor/github.com/vmware/vmw-guestinfo/vmcheck/vmcheck.go#L34-L37.
This is technically correct (as it avoids possible non-deterministic failures on port access), but it leads to all 2.x releases not working when kernel_lockdown is active.

**Comment by lucab** [comment]
The underlying library bug is tracked at https://github.com/vmware/vmw-guestinfo/issues/20. I posted a short-term hotfix at https://github.com/vmware/vmw-guestinfo/pull/21, which does alleviate the symptoms in Ignition in most cases.
Though, we likely need help from library owners for the longer-term solution, still pending.

**Comment by bgilbert** [comment]
This is not fixed upstream.  Reopening.

**Comment by miabbott** [comment]
Heh, we started carrying a patch in Fedora (https://src.fedoraproject.org/rpms/ignition/pull-request/91) just in time for the upstream PR to get merged - https://github.com/vmware/vmw-guestinfo/pull/21#event-6259243610

**Comment by bgilbert** [comment]
https://github.com/coreos/ignition/pull/1332 revendors vmw-guestinfo to pick up the upstream workaround.  Leaving this open to track a potential longer-term fix.
