### ISSUE TITLE
Support gzip for AWS EC2 instance user data

### ISSUE THREAD

**Issue by paulnivin** [coreos/ignition#1096]
# Feature Request #

## Environment ##

AWS

## Desired Feature ##

Ignition should support AWS EC2 instance user data returned as gzip-encoded.

AWS EC2 instance user data is an opaque blob limited to 16384 bytes prior to being stored as base64-encoded content. User data is commonly compressed as space is limited (e.g. cloud-init). While Ignition provides mechanisms to minimize the size of a config by utilizing external systems (e.g. S3), it would be useful to provide support for large self-contained Ignition configs on AWS without needing to manage or depend on the complexities of external systems.

## Other Information ##

Detecting a gzip-stream from user data and decompressing before sending to util.ParseConfig should be a straightforward change. If this feature request seems like a good idea, I can submit a PR.

**Comment by arithx** [comment]
I'd personally be fine with it. While large configs can be worked around by using `merge` configs it would be nice to also allow it to be self-contained in the userdata.

> Detecting a gzip-stream from user data and decompressing before sending to util.ParseConfig should be a straightforward change. If this feature request seems like a good idea, I can submit a PR.

Yeah, either of `util.ParseConfig` or `config.Parse` would work.

**Comment by bgilbert** [comment]
Closing per https://github.com/coreos/ignition/pull/1100#issuecomment-702364210.
