### ISSUE TITLE
Support reading from abitrary file locations on disk

### ISSUE THREAD

**Issue by crawford** [coreos/ignition#110]
This might mean adding support for file:// to coreos.config.url (what is the filesystem root in this case?) or maybe it's another parameter.

**Comment by vcaputo** [comment]
If we root the file url in the oem partition, it might be clearer to use oem as the scheme to communicate this more clearly.  i.e.
`oem:///ignition.json` uses `/ignition.json` from the oem partition.

**Comment by bassamtabbara** [comment]
For ramdisk scenarios there won't be a oem partition. /usr/share/oem is copied from cpio. Would be great if you supported that scenario as well.

**Comment by vcaputo** [comment]
In #111 I've made it so the oem partition is first tried @ /mnt/oem for the named path on oem:// urls, then /usr/share/oem is tried.
