### ISSUE TITLE
Consider supporting .d directory for base config fragments

### ISSUE THREAD

**Issue by bgilbert** [coreos/ignition#1101]
We're starting to have divergence between the FCOS and RHCOS base configs (https://github.com/coreos/fedora-coreos-config/pull/626), which requires the two distros to carry different `base.ign` files with common elements.  Consider supporting a `.d`-style base config directory, where Ignition walks the directory and merges every config fragment in it.

**Comment by bgilbert** [comment]
While we're here, we might also want to support an additional .d directory for each platform ID.

**Comment by lucab** [comment]
This looks like a useful generalization of the `base.ign` + `user.ign` merge :+1:.
Among other things, right now base & user configs are explicitly [identified by kind](https://github.com/coreos/ignition/blob/1a07e10a9c11bf11b4ebdd9cca6089fa58ca1cc0/internal/exec/engine.go#L76-L80). @bgilbert were you planning to have separate `base.d` and `user.d` paths, or to only touch the former, or to get rid of the split, or something else?

**Comment by bgilbert** [comment]
I was thinking this would only affect base configs for now.  For user configs I think there's value in maintaining the current model, with a single well-defined root config that explicitly merges sub-configs.  For base configs I think that's less important, since the "config built up from fragments" model is pretty well-understood in distro maintenance.
