### ISSUE TITLE
Consider maintaining terraform-provider-ignition 

### ISSUE THREAD

**Issue by Quentin-M** [coreos/ignition#1109]
Dear Red Hat,

It appears that Fedora CoreOS & Red Hat CoreOS both require Ignition v3. However, [terraform-provider-ignition](https://github.com/terraform-providers/terraform-provider-ignition) is stale since Dec 12, 2019. There has been a [slew](https://github.com/terraform-providers/terraform-provider-ignition/search?q=spec&type=issues) of issues related to support for various spec versions. 

I can't find any related requests in this repository, but it feels to me like Terraform support for Ignition v3 is pretty critical for adoption. For folks moving away from CoreOS Container Linux, and considering RH/Fedora CoreOS, given there is no Ignition v3 support in Terraform, the Flatcar choice may be easier then, which is not beneficial to your new ecosystem.

Also seeing some significant work for Ignition spec v3.2, which would then break again if anyone external was to contribute support into Terraform in any way different than what you guys are doing internally.

edit: found the following [PR](https://github.com/terraform-providers/terraform-provider-ignition/pull/69) to add support to the Terraform provider but it seems rather stale, why wouldn't Red Hat take over maintenance of the repository? Or yet.. how do people use Fedora/Red Hat CoreOS + Ignition if not using Terraform those days?

**Comment by travier** [comment]
As far as I know, Ignition v2 / spec 3+ support in now available in https://github.com/community-terraform-providers/terraform-provider-ignition.

**Comment by bgilbert** [comment]
@Quentin-M See https://github.com/terraform-providers/terraform-provider-ignition/pull/66 for the backstory.  Until such time as we hear back from upstream, we've been applying updates in [community-terraform-providers/terraform-provider-ignition](https://github.com/community-terraform-providers/terraform-provider-ignition).

**Comment by LorbusChris** [comment]
@Quentin-M we've also released the Ignition v2/spec v3 provider to the terraform provider registry: https://registry.terraform.io/providers/community-terraform-providers/ignition/latest
