### ISSUE TITLE
Ignition does not boot when IMDSv2 is set to required on AWS

### ISSUE THREAD

**Issue by wernerb** [coreos/ignition#1117]
# Bug #
Ignition does does not boot when IMDSv2 is set to required on AWS

## Operating System Version ##
32.20201004.3.0 
## Ignition Version ##
2.6.0
## Environment ##
On AWS eu-central-1 using official image ami-091d27df19b4e07f0

What hardware/cloud provider/hypervisor is being used to run Ignition?
HVM/Nitro 
## Expected Behavior ##

Using terraform to run and enforce metadata to IMDSv2 only:
```
  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required"
    http_put_response_hop_limit = 1
  }
```

No userdata is provided. Another attempt was done with p

## Actual Behavior ##

System does not boot, ignition shows:

```
See 'systemctl status ignition-fetch.service' for details.[    9.729902] ignition[467]: GET result: Unauthorized
```

Also tested with latest `testing` and `next` published AMIs

Full log here: https://gist.github.com/wernerb/14d10ec48a8f791e667d702631136ff6

## Reproduction Steps ##

  1. Launch an instance on AWS. Select to require IMDSv2 

## Other Information ##

It seems there is support added in https://github.com/coreos/ignition/pull/980

**Comment by arithx** [comment]
Tested w/ `32.20201004.3.0` (Ignition 2.6.0) and hit the same `GET result: Unauthorized` with & without specifying a config if IMDSv2 was forced.
