### ISSUE TITLE
Fix warnings from golangci-lint

### ISSUE THREAD

**Issue by bgilbert** [coreos/ignition#1121]
We should run golangci-lint over the Ignition codebase.  See https://github.com/coreos/coreos-assembler/issues/1813 for example output from Mantle.  @darkmuggle reports that the Ignition summary results are:

```
     50 (errcheck)
      9 (staticcheck)
      9 (gosimple)
      4 (deadcode)
      1 (unused)
      1 (structcheck)
      1 (ineffassign)
```

**Comment by arithx** [comment]
If we're going to implement `golangci-lint` we should definitely add it to the CI jobs that run as well 😄

**Comment by jlebon** [comment]
Should we have a similar issue for fcct?

**Comment by bgilbert** [comment]
Sure, filed as https://github.com/coreos/fcct/issues/149.
