### ISSUE TITLE
Consider moving ignition-firstboot-complete.service to fedora-coreos-config

### ISSUE THREAD

**Issue by jlebon** [coreos/ignition#1125]
Moved from discussions in https://github.com/coreos/ignition/pull/1124.

Right now, Ignition ships the service unit which deletes the `ignition.firstboot` stamp file:
https://github.com/coreos/ignition/blob/master/systemd/ignition-firstboot-complete.service

I'd like to propose moving that logic to fedora-coreos-config because the wiring for `/boot/ignition.firstboot` --> `ignition.firstboot` karg is a distro-specific thing (i.e. for FCOS, it's implemented by https://github.com/coreos/coreos-assembler/blob/d16e8df7b93a911a657f3e3eb989a75f084d6e25/src/create_disk.sh#L405 and https://github.com/coreos/coreos-assembler/blob/d16e8df7b93a911a657f3e3eb989a75f084d6e25/src/grub.cfg#L46-L57). So it seems cleaner to me to have the corresponding stamp removal also live on the distro side.

If we don't do this, then we should make it clear that Ignition expects from the distro that the `ignition.firstboot` karg is implemented via a stamp file at `/boot/ignition.firstboot` (which IMO seems highly prescriptive).

**Comment by cgwalters** [comment]
Makes sense to me.

**Comment by arithx** [comment]
Notably: we would also need to re-run zipl on s390x inside the initrd.
