### ISSUE TITLE
How to setup vlan tag

### ISSUE THREAD

**Issue by CC-Kuoying** [coreos/ignition#1142]
When I install bootstrap node, master nodes and worker nodes, I'd like to know how to setup vlan tag??

```
ip=192.168.129.106::192.168.129.1:255.255.255.0:worker3.okd4.example.local::none nameserver=192.168.129.100 coreos.inst.install_dev=/dev/sda coreos.inst.image_url=http://192.168.129.100:8080/okd4/fedoracoreos.raw.xz coreos.inst.ignition_url=http://192.168.129.100:8080/okd4/worker.ign
```

**Comment by bgilbert** [comment]
Hi, it sounds like you're looking for the [OKD discussion channels](https://www.okd.io/#contribute).  The user discussion list might be a good place to ask your question.
