### ISSUE TITLE
mandatory path for "swap" format filesystems

### ISSUE THREAD

**Issue by pjvleeuwen** [coreos/ignition#1150]
Based on the [FCCT Specification documentation](https://docs.fedoraproject.org/en-US/fedora-coreos/fcct-config/#_file_systems) it seems that:

* we can format a filesystem to be of "format: swap"
* the path is mandatory

As I understand one does normally not mount swap partitions, but correct me if I am mistaken.

I did find #354 which introduced this functionality and there I do not see any special treatment with regards to mounting. On the other hand I do not know if this was implemented later and (if so) where that would be implemented.

Either way it seems the documentation could use some clarification. Regardless I am reporting it for coreos/ignition to first check if this is a problem in the implementation as well.

PS: most relevant question for me personally: can I go ahead and use a swap partition in my FCC file?

**Comment by pjvleeuwen** [comment]
Based on [this line](https://github.com/coreos/ignition/blob/c39249c2d2146b5f3457f425fd59714c3e99a671/internal/exec/stages/mount/mount.go#L71) it seems the "path" node might not be mandatory in the implementation (or at least this bit of the implementation). Can somebody with a bit wider overview on the implementation comment on whether "path" is indeed optional in practice (and if "yes", move this issue to coreos/fedora-coreos-docs)?

**Comment by bgilbert** [comment]
The path is not mandatory; that's a docs bug.  Thanks for pointing it out.

You can create a swap partition from an FCC.  To enable it, you'll need to create a systemd swap unit or `fstab` entry yourself, since `with_mount_unit` doesn't handle that case.  I'll file an enhancement for that.

**Comment by bgilbert** [comment]
Docs PRs: https://github.com/coreos/ignition/pull/1151, https://github.com/coreos/fcct/pull/176

`with_mount_unit` issue: https://github.com/coreos/fcct/issues/177
