### ISSUE TITLE
Ignition file won't parse

### ISSUE THREAD

**Issue by verslyap** [coreos/ignition#1177]
# Bug #
I copied parts of an ignition file (see below) from the fedora-coreos documentation website and added the rest.  When I try to boot after installing or run the ignition-validator against it, it fails and give the output "error at line 1 col 2: invalid character 'v' looking for beginning of value"

## Operating System Version ##
The current stable branch v 33.20210301.3.1

## Ignition Version ##
1.3.0
## Environment ##

What hardware/cloud provider/hypervisor is being used to run Ignition?

## Expected Behavior ##
The boot succeds

## Actual Behavior ##
The boot halts and tries to go to the systemd emergency target.

## Reproduction Steps ##

  1. install fedora-coreos with coreos-installer install /dev/sda --copy-network --ignition-url <url>
  2. boot into coreos

## Other Information ##
Here is my ignition file
variant: fcos
version: 1.3.0
passwd:
  users:
    - name: adam
      groups:
        - wheel
        - docker
        - sudo
      password_hash: $y$j9T$g2abL7QA.Vk3XfTAEWr0G.$g9i0onKDt0iRB0gx0u5HQEuXnEuXo5xdV48FyEltey7
storage:
  files:
    - path: /etc/ssh/sshd_config.d/20-enable-passwords.conf
      mode: 0644
      contents:
        inline: |
          # Fedora CoreOS disables SSH password login by default.
          # Enable it.
          # This file must sort before 40-disable-passwords.conf.
          PasswordAuthentication yes

**Comment by bgilbert** [comment]
That's a Fedora CoreOS Config, not an Ignition config.  You'll need to [transpile it to an Ignition config](https://docs.fedoraproject.org/en-US/fedora-coreos/using-fcct/) using the Fedora CoreOS Config Transpiler.
