### ISSUE TITLE
Provide exported functions for parsing any config version less than N

### ISSUE THREAD

**Issue by bgilbert** [coreos/ignition#1190]
Ignition currently provides two sets of parse functions:
1. `config/Parse()`, which takes any 3.x config and returns the latest experimental version
2. `config/v3_*/Parse()`, which takes exactly one config version and returns that version

External users of the Go API usually want neither of these.  Option 1 forces them to consume structs containing who-knows-what experimental stuff, and option 2 doesn't support multiple config versions as input unless they try each version and call translation functions themselves.

What external callers actually want is to import the package for the most recent spec version they support, and call a function which accepts any config version up to and including that one.  We used to provide this behavior in the `spec2x` branch, but there was no way to turn it off, so callers that wanted to know the specific spec version (Mantle) had to painfully circumvent the automatic version detection.  Thus we removed the behavior in spec 3.

I'm proposing adding it back as optional behavior, by adding a second parse function to each config spec.  Essentially `config/config.go` would be drained into each of the individual specs, and `config/Parse()` would become a wrapper around the new parse function for the experimental spec.

cc @yuqi-zhang @LorbusChris

**Comment by dghubble** [comment]
@bgilbert @sohankunkerkar thanks for adding this. It substantially cleaned up some Go API uses https://github.com/poseidon/terraform-provider-ct/pull/116
