### ISSUE TITLE
Support CIFS volume mount

### ISSUE THREAD

**Issue by ms-choudhary** [coreos/ignition#1218]
# Feature Request #

Currently only these filesystem formats are supported: `"ext4", "btrfs", "xfs", "swap", "vfat"` . Would be great if we can add support for other mount types specifically: `cifs`. Would be happy to raise PR if you think this would be of some use. 

## Environment ##

We run OKD on Azure cloud, wanted to mount CIFS filesystem but ignition currently doesn't support it.

**Comment by bgilbert** [comment]
The `storage.filesystems` section is for creating a new filesystem on a block device, so there's no need to specify your `cifs` filesystem there.  Instead, you can use the `systemd.units` section to create a systemd mount unit for your filesystem.

**Comment by ms-choudhary** [comment]
Thanks for quick response. Will close this then.
