### ISSUE TITLE
disks: can't create disks/mounts under user's home directory

### ISSUE THREAD

**Issue by dustymabe** [coreos/ignition#1220]
# Bug #

If I want to create a disk partition and mount it under a user's home directory I get an error. Here is an example butane config: 

```
variant: fcos
version: 1.3.0
storage:
  disks:
    - device: /dev/sda
      wipe_table: false
      partitions:
        - number: 4
          label: root
          size_mib: 12000
          resize: true
        - number: 0
          label: containers
          size_mib: 10240
  filesystems:
    - path: /var/home/core/.local/share/containers
      device: /dev/disk/by-partlabel/containers
      format: xfs
      wipe_filesystem: false
      label: containers
      with_mount_unit: true
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAA...
```

In this case I'm trying to isolate the container storage for rootless podman for a particular user. I could create a mount point somewhere else (`/var/core-user-containers`) and symlink to it from here but, that isn't the easiest thing to do either because (on FCOS at least) I'd need to update SELinux to make it treat `/var/core-user-containers` like `/home/core/.local/share/containers`. So that's not just a simple workaround. 

Here is the error:

```
Starting Ignition (files)...
INFO     : Ignition 2.9.0
INFO     : Stage: files
INFO     : reading system config file "/usr/lib/ignition/base.d/00-core.ign"
DEBUG    : parsing config with SHA512: ff6a5153be363997e4d5d3ea8cc4048373a457c48c4a5b134a08a30aacd167c1e0f099f0bdf1e24c99ad180628cd02b767b863b5fe3a8fce3fe1886847eb8e2e
INFO     : reading system config file "/usr/lib/ignition/base.d/30-afterburn-sshkeys-core.ign"
DEBUG    : parsing config with SHA512: a30a1921169d5a3b58ef9b25de60783be1add6ea8d05fd44a0746cb60dd1b8a8b34ab51eec5eb14eecc2df2ab6ba1cd3fd7351eed65793d22316ab262a857d95
INFO     : no config dir at "/usr/lib/ignition/base.platform.d/qemu"
INFO     : files: ensureUsers: op(1): [started]  creating or modifying user "core"
DEBUG    : files: ensureUsers: op(1): executing: "useradd" "--root" "/sysroot" "--create-home" "--password" "*" "--comment" "CoreOS Admin" "--groups" "adm,sudo,systemd-journal,wheel" "core"
INFO     : files: ensureUsers: op(1): [finished] creating or modifying user "core"
INFO     : files: ensureUsers: op(2): [started]  adding ssh keys to user "core"
CRITICAL : files: ensureUsers: op(2): [failed]   adding ssh keys to user "core": failed to set SSH key: permission denied
```

The problem is that the directories for the mountpoint [are created](https://github.com/coreos/ignition/blob/89c9b9c74ebfae7f3d1bf1f3b425b6755e2f15ff/internal/exec/stages/mount/mount.go#L125) in ignition disks with `root:root` ownership and then later the `passwd` stage of `ignition-files` tries to [create the ssh keys as the user the ssh keys are for](https://github.com/coreos/ignition/blob/89c9b9c74ebfae7f3d1bf1f3b425b6755e2f15ff/internal/exec/util/passwd.go#L165-L183) (in this case the `core` user), which fails.

I tried to be clever and fix up the permissions on the created directories by adding `directories` entries in my Ignition config, but the `passwd` stage runs before that and it has no effect. 

## Operating System Version ##

FCOS at `34.20210427.3.0`.

## Ignition Version ##

`ignition-2.10.1-1.fc34.x86_64`

**Comment by arithx** [comment]
Hmm, is there any reason we couldn't/shouldn't just effectively do a `chown -R <user>:<group>` on the home directory (assuming one was specified to be created) after user creation and before we write the password hash / authorized keys ([inside the `ensureUsers` code](https://github.com/coreos/ignition/blob/main/internal/exec/stages/files/passwd.go#L71-L96))?

**Comment by dustymabe** [comment]
That could work. I think it would make sense especially for greenfield home directories. In the case where the home dir already existed (like someone re-using a home directory from a previous installation) it might not make sense, or we'd need to be careful.

**Comment by arithx** [comment]
From OOB conversations:

We've identified two potential solutions that each have their own tradeoffs:

1. During the `users` code look through all mountpoints and if any exist within the home directory of a user being created we chown that directory (and any parent directories that are inside the home directory) if they are currently owned by `root:root`. This solves the immediate problem but still has some corner cases where we could be changing permissions of previously existing directories.
2. During the `mount` stage we store any directories that are created for mountpoints. Then when inside the `users` code we know exactly which directories Ignition has created and can change ownership on any that are within the home directory. This commits a layering violation and also means that we could run into potential state issues in the future.

The general consensus was that we'd move forward with option 2 as it results in the more correct ownership changes.

It's worth noting that this change will only apply to directories within the home directory, for other directories created by mountpoints the ownership can be changed via a `directories` entry as mentioned in the post.

cc @jlebon @bgilbert
