### ISSUE TITLE
Reading large configs is very slow on QEMU

### ISSUE THREAD

**Issue by wagmarom1** [coreos/ignition#1259]
I'm using butane/ignition to config a directory which I like to copy into my Fedora core OS FS (I'm using Fedora WorkStation to create the FCOS image and booting using qemu). The system directory has some tarballs, I noticed that if this tarballs are big when I run the "cosa run" command it reach a step where the ignition job get stuck long time.

Here is the log 

```
[  OK  ] Finished CoreOS Ignition User Config Setup.

[   39.360570] audit: type=1130 audit(1630428492.157:23): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=coreos-ignition-setup-user comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

         Starting Ignition (fetch-offline)...

[   39.602930] systemd[1]: Starting Ignition (fetch-offline)...

[   39.892148] ignition[480]: Ignition 2.12.0

[   39.954751] ignition[480]: Stage: fetch-offline

[   40.038003] ignition[480]: reading system config file "/usr/lib/ignition/base.d/00-core.ign"

[   40.147829] ignition[480]: reading system config file "/usr/lib/ignition/base.d/30-afterburn-sshkeys-core.ign"

[   40.242617] ignition[480]: no config dir at "/usr/lib/ignition/base.platform.d/qemu"

[   40.316512] ignition[480]: no config URL provided

[   40.344945] ignition[480]: reading system config file "/usr/lib/ignition/user.ign"

[   40.424414] ignition[480]: no config at "/usr/lib/ignition/user.ign"

[   40.447610] ignition[480]: op(1): [started]  loading QEMU firmware config module

[   40.610668] ignition[480]: op(1): [finished] loading QEMU firmware config module

[  *** ] A start job is running for Ignition…etch-offline) (53min 8s / no limit)

```

**Reproduction steps**
1. Follow the steps here https://github.com/coreos/coreos-assembler/blob/main/docs/building-fcos.md
2. create the ignition file from this butane.bu. 
butane --pretty --strict --files-dir <butaneTest.bu dir> --output containers.ign

```
variant: fcos

version: 1.1.0

storage:

  trees:

    - local: <directoryWhereYourFilesAre>

      path: /etc/files

  files:

    - path: /etc/files/test.txt

      mode: 0600

      user:

        id: 500

      group:

        id: 501


```
3. cosa run -c -i containers.ign

**Expected behavior**
The files are copied into the /etc/files directory when the FCOS image is booted

**Actual behavior**
The boot is stuck in the ignition job

**System details**
 - QEMU.
 - Fedora CoreOS

**Ignition config**
{

  "ignition": {

    "version": "3.1.0"

  },

  "storage": {

    "files": [

      {

        "group": {

          "id": 501

        },

        "path": "/etc/files/test.txt",

        "user": {

          "id": 500

        },

        "contents": {

          "source": "data:,Hola!%0A"

        },

        "mode": 384

      },

      {

        "path": "/etc/files/docker-httpd.tar",

        "contents": {

          "compression": "gzip",

          "source": "data:;base64,H4sIAAAAAAAC/+z9B1AU2/cugH7d0zPTQ3KIgoAOOSiSg2IYggooiCIiJoKgEhQQFDEOiICICGZFEUVUMIERxYACgiKIWUQERcSEGbPyyp99/v85/u1769Wre6te1aXq1Petb6299tpr75nuHo7DdDuH0OkDrCxDpweF2jo4BFuHhNhOm2ZjZxdkOS1owLQBNtOsbOwdbKdbTg8aYGNlERwaZGkbOm2aVUhoSHCovYNl/7igOfjf/FhYWFjY2Nj8By0sLKTQxsrG1tpeSvutW1la21pBZIH/Cz9zY3+twOL/57n+XNz/n/wEh802/z89h4WFjYW9re1f9v+/99zSxtLCztrK1uqXbmlhYWkJke3/2///K/sfHBQ78//o/ltasO6/jbWtlZ2lBSytbWxt7e1tbOxsfsXbW9r9v9f//42fpcNGDScJ4r9sDobgl2XxkfyPLWZ0t3rF/4oRwwGyEEMbWuABoKTi/sSZ5L+R/q95fo/by+h/ohb+jYQUUv+L9WyqI/+FEP73OO4v0sDof+CqOzL/Qulx/5mvWP638Ada+HH+hdLjfvXmjfLvvr3R+zeqnGTW60v8axz5z7hBTPyofyOYsvFHPynmv0pG/xNd8W/8p4fe7XEhv7iFe4/f6/gDK5kB/+A/48a0x4Xw/r84Z8zyMJaZj60vwn74F/6z7+aRYcF2NuaRIWaRYbPnzjeb72BnZmfTPzaqv9V/ahIysSO8fP/rfJFSa1VhtF/+7oeh9xN3ezzvyz17j3/wXvqdPr0XcWmghZlQAYDAwoYn92usno4HlwtqQYhSUpaTd49WuLrCWaQEipQIXSUEBIREAvEbqMKJo+SRkagjdJ9JVXqCVhVrIYwAT5eaI5Gx49BJtDJNeI16oi4Wi3c7Uc6QEUos0t13rZDEJBrvJMHlzeTSAjEkMEZatpybSLOvIgU3w7EXJEK4QkfJVSQLrURQ5RDpu3pIJBLaO5Ans05EcYRqPLETV5hsIwzMoMVKTs7AdBFGiWkgzUJEhGR5Z7m4ujprJIrz1LLoYSIDEUdoDSvn4gkZKokSUjzO+fI/+0RXkhVCV/0NQohkssje60kxLRI7cUGsM4BMOq3yq8dyZJ6O0CLQQiQA0rKL6afUr2NI02KOGKLy4DQh4QzFmbJuzjvcsGmZpqvwfKAlCOckUj5rQgyBYkqcpq4iRJLWJZ6SaBky/WUIZ/UQN7QaExZZ6kJdZ2dLJTEHSIJcdAoNWMm5a1DeHOzNXgPykFBIbXUQ04S8KHaXhUj1mm7RWmeVsOscfVpBqNibkKhQpD4B1+E7oG6he8XZm6Y2iexAmNgIsY4639qqLyMGkQrXXfuJCe4qhU1CJ+fkaIhAiHkSZ4eBIjUFZzeV8pVCkYSQqIuuGKbflR+McjciZJSYSErOs0g0FopIC1dxhDPhOiblg1tgon7CzCTedbGxRDJEdbktzo9VkXzOKMwiRcRe3jctkhDr7IJBocib65YsydqVKBMsM1bxoROCnbNAe62DmljRW5xuDFA0ySHbRuX1x6CBUHQWA4YEIOtBSCi4WqSpO0DECZRNiva+Rlu4EtnCZGhJAgPlRCvJPDciGesgDFyxk/C2zlOx0KEAYZoQtDoSRfflnEcRhGjAMBslHQkgpI1FzjvhKqZ0k8QSmhCjUihqEE5wdU5UVVfcj2QqWTgmyfioDDUzA+IdK6h1pF45lU6DY/frlUQ4cQIlKIZ5FofSMwZHKI
....<this continue>
},

        "mode": 420

      }

    ]

  }

}

**Comment by bgilbert** [comment]
Reading the Ignition config from qemu is quadratic in the length of the config, since each read [costs](https://github.com/torvalds/linux/blob/0ee7c3e25d8c28845fceb4dd1c3cb5f50b9c45a9/drivers/firmware/qemu_fw_cfg.c#L150-L151) O(offset) and reads cannot be more than 4096 bytes.  Ignition is not optimizing its reads quite as well as it could, but for large configs, this problem is unavoidable.  To work around the issue, host your tarball in an external location and use an HTTPS URL in `source`.

**Comment by bgilbert** [comment]
`ioutil.ReadFile()` starts with a buffer size of 512 and eventually converges on the correct size (&ge; 4096).  A hand-rolled reimplementation can avoid the initial small `read(2)` calls, saving a grand total of 8 reads at the beginning where they don't affect performance very much.  I don't think the savings are worth carrying hand-rolled I/O code; closing.

**Comment by bgilbert** [comment]
I've posted the code anyway: https://github.com/coreos/ignition/pull/1260

**Comment by bgilbert** [comment]
If reading the config takes too long, #1260 now warns and starts reporting progress to make it clear what's happening.

**Comment by cgwalters** [comment]
The other thing you can do is use virtiofs.  xref https://github.com/coreos/coreos-assembler/issues/1812

**Comment by bgilbert** [comment]
@cgwalters Not seeing the connection here; could you elaborate?

**Comment by cgwalters** [comment]
> @cgwalters Not seeing the connection here; could you elaborate?

If you have some files locally on the host that you want to get into the VM, running a local HTTP server is certainly a standard way to do it, but is much less efficient (and if the files contain secrets, harder to secure) than having the guest read via virtio/9p.

**Comment by bgilbert** [comment]
@cgwalters That doesn't help in this case though, because Ignition configs can't source file contents from files elsewhere in the filesystem.
