### ISSUE TITLE
useradd/groupadd seg fault

### ISSUE THREAD

**Issue by n0rad** [coreos/ignition#1291]
I'm using ignition 0.31 (but I think the problem is the same on the latest looking at the code) with matchbox on PXE archlinux boot on bare metal to prepare machines and reboot to system.

To create group/user ignition is using `useradd`/`groupadd` with the `--root` parameter to target the root FS.
When libs between the PXE OS and the install OS differs useradd/groupadd seg fault.

```
...
CRITICAL : Ignition failed: failed to create users/groups: failed to create groups: failed to create group "autologin": signal: aborted (core dumped): Cmd: "/usr/sbin/groupadd" "--root" "/mnt" "--password" "*" "autologin" Stdout: "" Stderr: "*** stack smashing detected ***: terminated\n"
```

Running manually :
```bash
$ /usr/sbin/groupadd --root /mnt --password '*' autologin
*** stack smashing detected ***: terminated
[1]    64386 abort (core dumped)  /usr/sbin/groupadd --root /mnt --password '*' autologin
```

Running with strace :
<details>
<summary>$ strace /usr/sbin/groupadd --root /mnt --password '*' autologin</summary>
execve("/usr/sbin/groupadd", ["/usr/sbin/groupadd", "--root", "/mnt", "--password", "*", "autologin"], 0x7ffdf8fe6df8 /* 34 vars */) = 0
brk(NULL)                               = 0x564908c90000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffd92b34a70) = -1 EINVAL (Invalid argument)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=40460, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 40460, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff072c76000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libaudit.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=112408, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff072c74000
mmap(NULL, 180432, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ff072c47000
mprotect(0x7ff072c4a000, 98304, PROT_NONE) = 0
mmap(0x7ff072c4a000, 28672, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7ff072c4a000
mmap(0x7ff072c51000, 65536, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xa000) = 0x7ff072c51000
mmap(0x7ff072c62000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1a000) = 0x7ff072c62000
mmap(0x7ff072c64000, 61648, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7ff072c64000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`|\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0@\0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0"..., 80, 848) = 80
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0K@g7\5w\10\300\344\306B4Zp<G"..., 68, 928) = 68
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=2150424, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 1880536, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ff072a7b000
mmap(0x7ff072aa1000, 1355776, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x26000) = 0x7ff072aa1000
mmap(0x7ff072bec000, 311296, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x171000) = 0x7ff072bec000
mmap(0x7ff072c38000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bc000) = 0x7ff072c38000
mmap(0x7ff072c3e000, 33240, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7ff072c3e000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libcap-ng.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@ \0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=30600, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 32792, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ff072a72000
mprotect(0x7ff072a74000, 20480, PROT_NONE) = 0
mmap(0x7ff072a74000, 12288, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7ff072a74000
mmap(0x7ff072a77000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x5000) = 0x7ff072a77000
mmap(0x7ff072a79000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6000) = 0x7ff072a79000
close(3)                                = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff072a6f000
arch_prctl(ARCH_SET_FS, 0x7ff072a6f780) = 0
mprotect(0x7ff072c38000, 12288, PROT_READ) = 0
mprotect(0x7ff072a79000, 4096, PROT_READ) = 0
mprotect(0x7ff072c62000, 4096, PROT_READ) = 0
mprotect(0x5649076fa000, 4096, PROT_READ) = 0
mprotect(0x7ff072cae000, 8192, PROT_READ) = 0
munmap(0x7ff072c76000, 40460)           = 0
openat(AT_FDCWD, "/proc/sys/kernel/cap_last_cap", O_RDONLY) = 3
fstatfs(3, {f_type=PROC_SUPER_MAGIC, f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={val=[0, 0]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_NOSUID|ST_NODEV|ST_NOEXEC|ST_RELATIME}) = 0
read(3, "40\n", 7)                      = 3
close(3)                                = 0
brk(NULL)                               = 0x564908c90000
brk(0x564908cb1000)                     = 0x564908cb1000
openat(AT_FDCWD, "/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=3041456, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 3041456, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff072788000
close(3)                                = 0
getgid()                                = 0
getgid()                                = 0
setregid(0, 0)                          = 0
getuid()                                = 0
getuid()                                = 0
setreuid(0, 0)                          = 0
access("/mnt", F_OK)                    = 0
chdir("/mnt")                           = 0
chroot("/mnt")                          = 0
socket(AF_NETLINK, SOCK_RAW, NETLINK_AUDIT) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 4
connect(4, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(4)                                = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 4
connect(4, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(4)                                = 0
newfstatat(AT_FDCWD, "/etc/nsswitch.conf", {st_mode=S_IFREG|0644, st_size=312, ...}, 0) = 0
newfstatat(AT_FDCWD, "/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=312, ...}, AT_EMPTY_PATH) = 0
read(4, "# Name Service Switch configurat"..., 4096) = 312
read(4, "", 4096)                       = 0
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=312, ...}, AT_EMPTY_PATH) = 0
close(4)                                = 0
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=108313, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 108313, PROT_READ, MAP_PRIVATE, 4, 0) = 0x7ff07276d000
close(4)                                = 0
openat(AT_FDCWD, "/usr/lib/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P5\0\0\0\0\0\0"..., 832) = 832
newfstatat(4, "", {st_mode=S_IFREG|0755, st_size=51376, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 79320, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7ff072759000
mmap(0x7ff07275c000, 28672, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x3000) = 0x7ff07275c000
mmap(0x7ff072763000, 8192, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0xa000) = 0x7ff072763000
mmap(0x7ff072765000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0xb000) = 0x7ff072765000
mmap(0x7ff072767000, 21976, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7ff072767000
close(4)                                = 0
mprotect(0x7ff072765000, 4096, PROT_READ) = 0
munmap(0x7ff07276d000, 108313)          = 0
openat(AT_FDCWD, "/etc/group", O_RDONLY|O_CLOEXEC) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=751, ...}, AT_EMPTY_PATH) = 0
lseek(4, 0, SEEK_SET)                   = 0
read(4, "root:x:0:root\nsys:x:3:bin\nmem:x:"..., 4096) = 751
read(4, "", 4096)                       = 0
close(4)                                = 0
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=108313, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 108313, PROT_READ, MAP_PRIVATE, 4, 0) = 0x7ff07276d000
close(4)                                = 0
openat(AT_FDCWD, "/usr/lib/libnss_systemd.so.2", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@`\0\0\0\0\0\0"..., 832) = 832
newfstatat(4, "", {st_mode=S_IFREG|0755, st_size=235528, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 240056, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7ff07271e000
mprotect(0x7ff072724000, 200704, PROT_NONE) = 0
mmap(0x7ff072724000, 151552, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x6000) = 0x7ff072724000
mmap(0x7ff072749000, 45056, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x2b000) = 0x7ff072749000
mmap(0x7ff072755000, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x36000) = 0x7ff072755000
close(4)                                = 0
openat(AT_FDCWD, "/usr/lib/libdl.so.2", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20\22\0\0\0\0\0\0"..., 832) = 832
newfstatat(4, "", {st_mode=S_IFREG|0755, st_size=18608, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 20624, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7ff072c7a000
mmap(0x7ff072c7b000, 8192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x1000) = 0x7ff072c7b000
mmap(0x7ff072c7d000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x3000) = 0x7ff072c7d000
mmap(0x7ff072c7e000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x3000) = 0x7ff072c7e000
close(4)                                = 0
openat(AT_FDCWD, "/usr/lib/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\201\0\0\0\0\0\0"..., 832) = 832
pread64(4, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\307Y\373z\3054\277z\21\35\225\341\273\304<\223"..., 68, 824) = 68
newfstatat(4, "", {st_mode=S_IFREG|0755, st_size=158744, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 135600, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7ff0726fc000
mmap(0x7ff072703000, 65536, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x7000) = 0x7ff072703000
mmap(0x7ff072713000, 20480, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x17000) = 0x7ff072713000
mmap(0x7ff072718000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x1b000) = 0x7ff072718000
mmap(0x7ff07271a000, 12720, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7ff07271a000
close(4)                                = 0
mprotect(0x7ff072718000, 4096, PROT_READ) = 0
mprotect(0x7ff072c7e000, 4096, PROT_READ) = 0
mprotect(0x7ff072755000, 12288, PROT_READ) = 0
set_tid_address(0x7ff072a6fa50)         = 64419
set_robust_list(0x7ff072a6fa60, 24)     = 0
rt_sigaction(SIGRTMIN, {sa_handler=0x7ff072703b90, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7ff0727100f0}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {sa_handler=0x7ff072703c30, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0x7ff0727100f0}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
writev(2, [{iov_base="*** ", iov_len=4}, {iov_base="stack smashing detected", iov_len=23}, {iov_base=" ***: terminated\n", iov_len=17}], 3*** stack smashing detected ***: terminated
) = 44
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff072c79000
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
getpid()                                = 64419
gettid()                                = 64419
tgkill(64419, 64419, SIGABRT)           = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=64419, si_uid=0} ---
+++ killed by SIGABRT (core dumped) +++
[1]    64416 abort (core dumped)  strace /usr/sbin/groupadd --root /mnt --password '*' autologin
</details>

Libs :
``` bash
$ ldd /usr/sbin/groupadd
        linux-vdso.so.1 (0x00007ffc06d16000)
        libaudit.so.1 => /usr/lib/libaudit.so.1 (0x00007efcd7415000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007efcd7249000)
        libcap-ng.so.0 => /usr/lib/libcap-ng.so.0 (0x00007efcd7240000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007efcd7464000)
$ ldd /mnt/usr/sbin/groupadd
        linux-vdso.so.1 (0x00007ffc7b783000)
        libaudit.so.1 => /usr/lib/libaudit.so.1 (0x00007f59ba5fc000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f59ba430000)
        libcap-ng.so.0 => /usr/lib/libcap-ng.so.0 (0x00007f59ba427000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f59ba64b000)
```

I don't know exactly how useradd/groupadd are working but it look like using `--root` makes them mixing libraries between the host OS and the install OS.

But this is working as expected. (Note that I'm targeting host binary :roll_eyes: ).
```bash
$ /mnt/lib/ld-linux-x86-64.so.2 --library-path /mnt/lib/ /usr/sbin/groupadd --root /mnt toto42
```

**Comment by bgilbert** [comment]
So, a couple things here:

- Ignition 0.x is unsupported upstream.  Flatcar Container Linux still uses it, but all other applications should be running Ignition 2.x.
- Ignition is intended to run in an initramfs built from the installed system, so the libraries in the two environments shouldn't generally differ very much.  (Depending how and when the initramfs is generated, they might differ to a small degree.)

Your description of your use case suggests that you're doing something unusual.  Could you provide more details on your deployment scenario, and where you're getting your copy of Ignition?

**Comment by bgilbert** [comment]
It appears likely that Ignition is being used in a way it wasn't designed for, and the reporter hasn't responded to a request for more info, so I'll close this.  Feel free to reopen if you can provide additional info.
