### ISSUE TITLE
CoreOS confuse in case of multiple disk with RAID-1

### ISSUE THREAD

**Issue by ShashankNEC** [coreos/ignition#1295]
Hi Team,

We have installed CoreOS in our OCP ENV with RAID-1 but the disk which we are passing in the ignition file are not used for OS, It is picking random disk may be it got confused in case of multiple disk.

We have tried the same config in case of server having only two disk there it is working fine.

We are using below config to install coreOS.

******************************************************
:172.19.4.16
    kernel http://172.19.4.5:8000/ipxe/rhcos-4.8.2-x86_64-live-kernel-x86_64 \
    ip=enp130s0f0:none:9000 \
    ip=enp130s0f1:none:9000 \
    ip=bond0:none:9000 \
    bond=bond0:enp130s0f0,enp130s0f1:mode=802.3ad,xmit_hash_policy=layer3+4,lacp_rate=fast,miimon=100,updelay=200,downdelay=200 \
    ip=172.19.4.16:::255.255.252.0:auh-akb02-rk01-dell-ocst03.caas6.st00.etisalat-nfvi.local:eno3:none:1476 \
    vlan=bond0.2504:bond0 \
    ip=172.19.0.16::172.19.3.254:255.255.252.0::bond0.2504:none:9000 \
    vlan=bond0.2502:bond0 \
    ip=172.19.8.16:::255.255.252.0::bond0.2502:none:9000 \
    vlan=bond0.2507:bond0 \
    ip=10.179.237.16:::255.255.255.0::bond0.2507:none:9000 \
    vlan=bond0.2505:bond0 \
    ip=10.179.240.12:::255.255.252.0::bond0.2505:none:9000 \
    vlan=bond0.2506:bond0 \
    ip=10.179.244.12:::255.255.252.0::bond0.2506:none:9000 \
    bootdev=eno3 \
    rd.neednet=1 \
    nameserver=172.19.0.1 \
    nameserver=172.19.0.6 \
    initrd=rhcos-4.8.2-x86_64-live-initramfs.x86_64.img \
    coreos.inst=yes \
    coreos.inst.install_dev=/dev/sda \
    coreos.live.rootfs_url=http://172.19.4.5:8000/caas/rhcos/images/latest/rhcos-4.8.2-x86_64-live-rootfs.x86_64.img \
    coreos.inst.ignition_url=http://172.19.4.5:8000/caas/rhcos/ignitions/worker.ign
    initrd http://172.19.4.5:8000/ipxe/rhcos-4.8.2-x86_64-live-initramfs.x86_64.img
    boot

*******************************************

Please help

**Comment by jlebon** [comment]
Hi @ShashankNEC, it's hard to tell what's going on without more information. It looks like you are an OCP customer. Please instead reach out to Red Hat Support to open a case. Make sure to include system details, reproduction steps, and logs in your report.

Thanks!
