### ISSUE TITLE
network: interface goes down

### ISSUE THREAD

**Issue by greenpau** [coreos/ignition#132]
Initially, the interface look good and work find:

```
3: ens1f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether a0:48:1c:b9:9b:a0 brd ff:ff:ff:ff:ff:ff
    inet 10.187.10.10/24 brd 10.187.10.255 scope global ens1f0
       valid_lft forever preferred_lft forever
    inet6 fe80::a248:1cff:feb9:9ba0/64 scope link 
       valid_lft forever preferred_lft forever
```

However, after some period or scheduled updates, the interface shows `DOWN`. Importantly, the switch it is connected to shows UP.

```
core@td-np10 ~ $ ip link show dev ens1f0
3: ens1f0: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether a0:48:1c:b9:9b:a0 brd ff:ff:ff:ff:ff:ff
core@td-np10 ~ $ 
core@td-np10 ~ $ sudo ip link set dev ens1f0 up
RTNETLINK answers: N
```

Please assisnt

**Comment by crawford** [comment]
So, the network is up after the first boot. Does it go down whenever the machine reboots or will it go down after some amount of time (e.g. ~1 hour)? Can I see the networkd section of your config?

**Comment by vcaputo** [comment]
It may also be illuminating to see the output of `journalctl -t systemd-networkd`.

**Comment by greenpau** [comment]
here is what Solarflare support said:

Hi Paul,

From the error shown in the sfreport 

```
[21810.287997] NETDEV WATCHDOG: ens1f0 (sfc): transmit queue 10 timed out
[21811.341448] sfc 0000:08:00.0 ens1f0: TX stuck with port_enabled=1: resetting channels
[21811.377861] sfc 0000:08:00.0 ens1f0: resetting (RECOVER_OR_ALL)
```

the netdev watchdog timer has kicked in. The NETDEV WATCHDOG fires when TX events are not serviced within a given time frame.
In the past we saw this sort of issue happen due to serial logging being enabled. 

```
Kernel Command Line:init=/usr/lib/systemd/systemd rootflags=rw mount.usrflags=ro init=/usr/lib/systemd/systemd console=ttyS0,115200n8 console=tty0 ro noswap cros_legacy root=LABEL=ROOT rootflags=subvol=root usr=gptprio: usr=PARTUUID=7130c94a-213a-4e5a-8e26-6cce9662f132 
```

This can cause the network cards interrupts to not be processed, and cause the watchdog to fire because it takes several seconds to signal back completion. Also If the switch is constantly sending pause frames; preventing the card from completing a send; then this is one legitimate cause of the TX watchdog firing.

Our driver tried to recover but failed for some reason. It will be beneficial for us if you can send us the full kernel messages that surrounds the above error. Other drivers in the systm may also have this issue.

You can try removing serial logging from the kernel command line in /boot/grub/grub.conf.

I also noticed that you are using a very old driver and firmware

```
name    address                driver_version controller_version
ens1f1 0000:08:00.1       4.0          4.0.6.6702 rx1 tx1
```

we highly recommend to update these as many fixes and enhancements were added since then.

To update the firmware please download Linux utilities from here:

https://support.solarflare.com/index.php?view=categories&id=1945&option=com_cognidox&Itemid=11

Version: v4.6.6.1002 part no: SF-107601-LS
Please also have a look at the release note.

unzip the file, and install, as root,  as follows:

```
# rpm -ivh <rpm file>
```

run sfupdate utiltiy as root

```
#sfupdate 
```

It should print out the current version of your adapter and instructions how to update it. Please also consult the Server Adapter guide (please see below for instruction on downloading the guide)

You can also find the driver her: https://support.solarflare.com/index.php?view=categories&id=1945&option=com_cognidox&Itemid=11
Version: v4.5.1.1020 part no:SF-103848-LS

Please follow the instructions in the Adapter user guide page 14, section Building the source RPM, which you can download from here: https://support.solarflare.com/index.php?view=categories&id=1945&option=com_cognidox&Itemid=11
Part no: SF-103837-CD issue:14

**Comment by vcaputo** [comment]
Judging from Solarflare's response this appears to be a network device/firmware/driver issue, not anything ignition-related.

I would try the firmware update as suggested and go from there.

**Comment by crawford** [comment]
This issue was moved to coreos/bugs#475
