### ISSUE TITLE
/etc/systemd/system-preset/20-ignition.preset is not reproducible

### ISSUE THREAD

**Issue by mkenigs** [coreos/ignition#1339]
# Bug #

## Ignition Version ##
Ignition v2.13.0-32-g9132ad09

## Environment ##

I ran ignition-liveapply in an OpenShift build with two different inputs, but I only changed files and didn't touch systemd units

## Expected Behavior ##
/etc/systemd/system-preset/20-ignition.preset is the same for both runs

## Actual Behavior ##
/etc/systemd/system-preset/20-ignition.preset contains the same services in a different order

**Comment by jlebon** [comment]
See also https://github.com/coreos/ignition/issues/588 which would have Ignition stop using presets entirely.
