### ISSUE TITLE
timeout on aws

### ISSUE THREAD

**Issue by mischief** [coreos/ignition#134]
on CoreOS alpha 808.0.0 with ignition 0.1.6 i get a timeout on aws and enter the emergency console. this only happened once out of a few hundred ec2 instances.

log is at https://gist.github.com/mischief/5cda3808918187e6b09d

**Comment by crawford** [comment]
This looks like a continuation of https://github.com/coreos/ignition/issues/118, though, obviously a different root cause.

**Comment by mischief** [comment]
it appears the network came up just 2 seconds after ignition failed. aws :-1:

**Comment by crawford** [comment]
OK, so it sounds like we need to up the AWS timeout to infinity. Though, if we do that, users won't have access to log-entries after three minutes (AWS arbitrarily cuts it of at three minutes).

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/ignition/pull/135.
