### ISSUE TITLE
Support Butane’s YAML format natively

### ISSUE THREAD

**Issue by aral** [coreos/ignition#1483]
# Feature Request #

Unless I’m mistaken, the workflow for creating CoreOS configurations is:

1. Write your configuration in YAML
2. Run a tool (Butane) to transpile them into JSON
3. Pass the resulting JSON to ignition

If so, what I don‘t understand is why step 2 is necessary.

Ignition should handle that transpilation as an implementation detail. (Or just parse the YAML directly). Why make everyone jump through another hoop? (Especially when compared to the competition, e.g., cloud-init, where you don’t have to this additional step/effort.)

## Environment ##

Testing CoreOS with vultr.

## Desired Feature ##

Have ignition use Butane’s YAML format directly. Remove the need for Butane.

## Other Information ##

n/a

**Comment by bgilbert** [comment]
Separating the user-facing configuration language and tool from the provisioning code provides a lot more flexibility than if everything is done at runtime.  Butane can validate a user config, syntactically and to some extent semantically, without needing to go to the trouble of booting a node.  Also, a separate frontend (whether Butane or another tool) can provide additional features like custom configuration directives without those needing to be supported by the OS itself.  For example, Butane has directives for embedding local files and directory trees into the config at transpilation time, and there's discussion of adding templating directives (coreos/butane#111) so configs can easily be customized for different types of nodes.
