### ISSUE TITLE
provider: support Linode cloud provider

### ISSUE THREAD

**Issue by tormath1** [coreos/ignition#1508]
# Feature Request #

As discussed on IRC, it would be interesting to investigate on getting [Linode][linode] supported by Ignition. The difficulty relies on the fact that Linode does not have common mechanism like IMDS for supplying userdata.

(It could also help to get Linux distro using Ignition to be available on this provider (like FCOS, Flatcar, MicroOS, etc.) but that's another story.) 

## Environment ##

There is not yet a straight forward way to install FCOS nor Flatcar on Linode. I installed Flatcar following this blogpost: https://alfter.us/2021/09/20/installing-flatcar-container-linux-on-linode/. Ignition configuration is provided during the installation of the OS on the disk, I would assume it's the same thing for FCOS. In the end, it's not that flexible to update the configuration.

## Desired Feature ##

The idea would be to define the Ignition configuration inside a [StackScript][stackscript], during the boot Ignition will fetch the configuration from the StackScript and process as usual.

## Other Information ##

* https://github.com/linode/linodego
* https://discussion.fedoraproject.org/t/coreos-on-linode/41007
* it takes a token to use `linodego`, not sure if a token is available during the boot

[linode]: https://www.linode.com/
[stackscript]: https://www.linode.com/docs/guides/writing-scripts-for-use-with-linode-stackscripts-a-tutorial/

**Comment by prestist** [comment]
Yeah, after reviewing Linode and its workflow of using custom img's which makes getting ignition file data into an instance difficult. It might be prudent to not pursue this further until support is added for user data or our model changes.

**Comment by travier** [comment]
> Historically, StackScripts worked by replacing /usr/sbin/getty with the script, and then having the script restore getty afterward. On image-based OSes like the ones Ignition is designed for, that approach will not work. However, I haven't found any recent info on whether StackScripts still function that way.

Found that in: https://www.linode.com/community/questions/10693/stackscripts-api#answer-50530

**Comment by nesv** [comment]
Linode (Akamai Connected Cloud) now provides a metadata service in some regions: https://www.linode.com/docs/products/compute/compute-instances/guides/metadata/.
