### ISSUE TITLE
Unable to fetch remote ignition config - Flatcar

### ISSUE THREAD

**Issue by kallisti5** [coreos/ignition#1514]
# Feature Request #

Users should be able to use a remote ignition configuration.

## Environment ##

* Bare Metal, Flatcar stable
* coreos-install -d /dev/nvme1n1 -i kickoff-nas.ign
  *  https://raw.githubusercontent.com/kallisti5/ignition/main/ign/kickoff-nas.ign
 * Reboot
   * "Failed to fetch config: resource requires networking"
   * GET error: Get "https://raw......"
 
## Desired Feature ##
  * It should be possible to fetch a remote config.  A networking card supported by flatcar is installed... however networking seems to be inactive while processing pre-packed ignition configs?

**Comment by jlebon** [comment]
Ignition indeed supports fetching remote resources. The error message you're getting should be non-fatal; it's part of the infrastructure for conditional networking (see https://github.com/coreos/ignition/pull/956 for details). That error means that offline fetching was attempted but failed and that full networking is required. If the OS is configured correctly, this should signal to the initramfs to bring up networking and try fetching again. The details here depend on the OS, so I'll let Flatcar devs chime in here. @pothos perhaps?

**Comment by jlebon** [comment]
It'd also help if you could post the full console logs if possible.
