### ISSUE TITLE
Support Hyper-V

### ISSUE THREAD

**Issue by bgilbert** [coreos/ignition#1538]
Hyper-V has [Hyper-V Integration Services](https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/integration-services) for host-guest communication.  It's possible to [write a custom service](https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/make-integration-service), but that requires a host-side process to connect to a socket.  But there's also a [key-value service](https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/integration-services#hyper-v-data-exchange-service-kvp) ([documentation](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn798287(v=ws.11))).

The key-value service does work on Linux, with a [helper daemon](https://github.com/torvalds/linux/blob/master/tools/hv/hv_kvp_daemon.c) shipped with the kernel source.  Unlike the other hypervisors we support, the daemon appears to take the passive role; it connects and listens for get/set commands, maintaining a set of binary blob [files](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn798287(v=ws.11)#pool-structure) in `/var`.

In principle, we can emulate the daemon: connect to the hypervisor socket, wait for a SET command for the correct key, then close the socket and continue.  If we don't get the Ignition config in the initial set of keys, assume there isn't one.  This involves a timeout, which isn't ideal, but the scope of the timeout is much more constrained than "all hardware detection has completed" as would be needed for a config drive.

The kernel headers give the [appearance](https://github.com/torvalds/linux/blob/7c46948a6e9cf47ed03b0d489fde894ad46f1437/include/uapi/linux/hyperv.h#L189) of a 2 KiB limit on the value size, which a) is cramped but sufficient for our purposes, and b) may not be a real limit in the wire protocol; we should test this.

Proposed next steps:

- [ ] Try to get a custom key/value pair into the guest using `hv_kvp_daemon`
- [ ] Try stopping the daemon, removing its data files, restarting it, and seeing whether the data is restored.  This verifies that the host service doesn't require data persistence in the guest.  If it did, Ignition's use of the K-V protocol would interfere with any `hv_kvp_daemon` instance run later in the real root.
- [ ] Implement K-V socket in Ignition
- [ ] Determine the maximum value size we can receive

https://github.com/coreos/fedora-coreos-tracker/issues/251 discusses Hyper-V support in FCOS.

**Comment by bgilbert** [comment]
Just to make this explicit: an Ignition implementation can't be directly adapted from `hv_kvp_daemon.c` because the latter is GPLv2 and Ignition is Apache.

**Comment by bgilbert** [comment]
It appears that KVP values are limited to 1K characters (2K bytes in UTF-16).  In OOB discussion we concluded that the least-worst approach was to support concatenating multiple keys together.  OSes can document a PowerShell script that takes an Ignition config, chunks it, and sets the appropriate KVP keys.

**Comment by bgilbert** [comment]
Open questions:
- How should the KVP keys be named/structured?
- Is the Hyper-V socket interface accessible to non-root users or in a container?
- Does the guest have an API to delete the host's KVP keys?  (I assume no.)
- Are the KVP keys deleted in the host (in the registry etc.) if the VM is deleted?

**Comment by prestist** [comment]
This was achieved by https://github.com/coreos/ignition/pull/1555
