### ISSUE TITLE
Add support for fetching the user data with the VersionId

### ISSUE THREAD

**Issue by canassa** [coreos/ignition#596]
# Feature Request #

## Environment ##

This applies to EC2 instances fetching the userdata from a S3 bucket

## Desired Feature ##

It would be nice if the `FetchFromS3` function could also take the VersionID of the S3 file in consideration when fetching the userdata from S3. Something like this:

at: `internal/resource/url.go`
```diff
 	sess.Config.Region = aws.String(region)
 
+	var versionId *string
+	if v, ok := u.Query()["versionId"]; ok {
+		versionId = &v
+	}
+
 	input := &s3.GetObjectInput{
-		Bucket: &u.Host,
-		Key:    &u.Path,
+		Bucket:    &u.Host,
+		Key:       &u.Path,
+		VersionId: versionId,
 	}
 	err = f.fetchFromS3WithCreds(ctx, dest, input, sess)
 	if err != nil {
```

## Other Information ##

My use case for this is Terraform. Everytime I execute a deployment with Terraform and the instance has it's data store in a S3 bucket, Terraform replaces the whole instance because Terraform assumes that the userdata might have changed. This causes several instances to be replaced even when their userdata has not changed.

**Comment by lucab** [comment]
This feature request seems reasonable to me, barring some integration doubts below.

> Terraform replaces the whole instance because Terraform assumes that the userdata might have changed.

I'm not exactly sure I'm following what's happening here. Are you overwriting the S3 objects via terraform? Did you already check the behavior with object versioning enabled? I'm just confused as to why you want to patch ignition to workaround terraform behavior. Ignition only runs once when the node is first booted, so with versioning enabled I think it should (currently) always use the latest version of an object (latest at the time of fetching it).

**Comment by canassa** [comment]
I have a Terraform project that controls several groups of CoreOS EC2 instances, each one of those groups has a different Userdata which is generated by the Terraform ignition provider.

Terraform is usually able to detect that a Userdata of a specific group has changed and only mark that group of machines to be replaced, leaving the rest alone.

My problem started once I migrate to storing the Userdata in an S3 bucket, I noticed that Terraform was no longer able to detect if a Userdata has changed or not, therefore it always assumes that I have changed causing all my instances to be replaced even when their Userdata is exactly the same.

I am not a Terraform expert, just a user, but I think that their reasoning makes sense; unless there is a way to grab a specific version of an S3 file, there is no way to know if it's content remains the same or not.

If this feature request is accepted and delivered, it will be followed by another one in Terraform itself adding support for passing the VersionID to the S3 file of the Userdata

Thanks!

**Comment by lucab** [comment]
Thanks for the follow-up, I got the full picture now. Would you like to submit the PR for this yourself? We'll happily review that.

For future reference, I double-checked some other official parser for the `s3://` uri and indeed a `versionId` query parameter is the canonical way for passing this option ([ref](https://github.com/aws/aws-sdk-java/blob/542d678880b3d8d1ba32d2bd630d0f0bd695ff59/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3URI.java#L192) from aws-java-sdk).

**Comment by canassa** [comment]
I will be glad to send a PR, is there documentation on how to build the project and run the tests? Otherwise, I can try to figure out things by myself.
