### ISSUE TITLE
Support conditional user creation

### ISSUE THREAD

**Issue by cgwalters** [coreos/ignition#600]
Splitting this out of discussion here:

https://github.com/coreos/coreos-metadata/pull/90#discussion_r202438581

Today CL precreates a `core` user.  Not all distributions will want to do that; I personally prefer the cloud-init semantic where it has a default user that's created *dynamically* if and only if you do not specify a different username.

I suspect for most people who are defining a different user with Ignition than `core` for CL, the `core` user is unused.  And it could be a source of conflict if the machine is joined to a LDAP domain or whatever that happens to have a `core` user.

**Comment by ajeddeloh** [comment]
I don't really like the idea of conditional anything in Ignition; it's a declarative spec. We're not perfect at it, but it's what we aim for. What we can do is something akin to (and simpler than) the [partition reuse semantics](https://coreos.com/ignition/docs/latest/operator-notes.html#partition-reuse-semantics). This would enable a config to say `core` should not exist (and whether it should be deleted or Ignition should fail if it does) and that another user should exist.

Thoughts?

**Comment by bgilbert** [comment]
My understanding of the proposal is that Ignition would create the `core` user only if no other users are specified in the config.  So the config would still be self-contained, just weirdly implicit.

But yeah, adding the ability to delete users does seem like a nice solution.

**Comment by ajeddeloh** [comment]
Given how we changed fcos to create `core` via the Ignition base config, Is this now part of https://github.com/coreos/ignition/issues/738? @cgwalters

**Comment by cgwalters** [comment]
Yeah, fine to close this in favor of #738 from my PoV.
