### ISSUE TITLE
Default files.overwrite to false

### ISSUE THREAD

**Issue by bgilbert** [coreos/ignition#604]
# Feature Request #

## Environment ##

Any

## Desired Feature ##

`files.overwrite` defaults to true, unlike `directories.overwrite` and `links.overwrite`.  Default `files.overwrite` to false for spec 3.0.

**Comment by sayanchowdhury** [comment]
@aavrug has expressed interest to solve this issue during code hack last weekend.

**Comment by dustymabe** [comment]
@sayanchowdhury @aavrug is that still the case. We're going to want to have this in pretty soon.

**Comment by dustymabe** [comment]
@rfairley has agreed to pick this one up.
