### ISSUE TITLE
Ignition config translation does not set `wipeFilesystem`

### ISSUE THREAD

**Issue by Rahuls0720** [coreos/ignition#607]
# Bug #

## Operating System Version ##
Any

## Ignition Version ##
Spec versions 1.x and 2.0.0

## Environment ##
Any

## Expected Behavior ##
Ignition configs translated from 2.0.0 (or below) to a 2.1.0 should set `wipeFilesystem = true`.  Config versions 2.0.0 (and below) always wipe the file system.

## Actual Behavior ##
Ignition configs translated from 2.0.0 (or below) to a 2.1.0 have wipeFilesystem set to its default value of false.

**Comment by bgilbert** [comment]
Ignition configs &le; 2.0.0 are not intended to unconditionally wipe a filesystem by default.  If that behavior is desired, the now-deprecated `filesystems.mount.create.force` option can be set to `true`.

**Comment by Rahuls0720** [comment]
Thanks @bgilbert, I didn't realize that. Will close this.
