### ISSUE TITLE
`ignition --help` returns non-zero return code

### ISSUE THREAD

**Issue by dustymabe** [coreos/ignition#614]
# Bug 

```
[root@vanilla-f28 artifacts]# ignition --help
Usage of ignition:
  -clear-cache
        clear any cached config
  -config-cache string
        where to cache the config (default "/run/ignition.json")
  -fetch-timeout duration
        initial duration for which to wait for config (default 1m0s)
  -log-to-stdout
        log to stdout instead of the system log when set
  -oem value
        current oem. [azure brightbox cloudsigma cloudstack digitalocean ec2 exoscale file gce hyperv interoute niftycloud openstack packet pxe qemu rackspace rackspace-onmetal vagrant vagrant-virtualbox virtualbox vmware]
  -root string
        root of the filesystem (default "/")
  -stage value
        execution stage. [disks files]
  -version
        print the version and exit
[root@vanilla-f28 artifacts]# echo $?
2
```

See the non-zero return code above ^^ 

## Operating System Version ##
Fedora 28

## Ignition Version ##

```
[root@vanilla-f28 artifacts]# ignition --version
Ignition 0.27.0
```

RPM file [here](https://kojipkgs.fedoraproject.org//work/tasks/283/29090283/ignition-0.27.0-2.gitcc7ebe0.fc30.x86_64.rpm). Koji scratch build [here](https://koji.fedoraproject.org/koji/taskinfo?taskID=29090283)

**Comment by ajeddeloh** [comment]
Ignition uses the golang standard library `flag` package. We don't define our own `--help`, we just get it for free from `flag`. I don't see a strong reason to support this either. You probably shouldn't be running Ignition interactively :scream: .

**Comment by ajeddeloh** [comment]
@dustymabe thoughts?

**Comment by jlebon** [comment]
Ahh I see, it does support `-h`/`-help` (since it doesn't print the `flag provided but not defined`), but it still returns rc=2, which does seem odd.

**Comment by dustymabe** [comment]
i think i understand now. it's because we don't define `--help` at all and `flag` is just spitting back out to us a "usage" since we provided a flag that was unknown ?

**Comment by jlebon** [comment]
IIUC, it doesn't understand `--help`, but it understands `-help` and `-h`. It's just that it still returns rc=2.

**Comment by ajeddeloh** [comment]
Well kind of. Looks like `flags.Parse` (from go's stdlib) is what's exiting with rc=2. It appears to special case -h/--help/-help to not print the "unknown flag" error and just print the usage and `exit(2)`.

**Comment by ajeddeloh** [comment]
@jlebon `-h`, `--help`, and `-help` all behave the same for me (go 1.10)

**Comment by ajeddeloh** [comment]
I don't think this is worth deviating from the default go flags behavior, closing.
