### ISSUE TITLE
Kola AWS test failure: nfs unit not enabled

### ISSUE THREAD

**Issue by yuqi-zhang** [coreos/ignition#624]
# Bug #

## Operating System Version ##

Red Hat CoreOS 4.0.4760 

## Ignition Version ##

Ignition 0.27.0

## Environment ##

AWS (ami: ami-0fc9356f07902b569)

## Expected Behavior ##

Active var-mnt.mount in rhcos.linux.nfs.v4 test: https://github.com/coreos/mantle/blob/master/kola/tests/misc/nfs.go#L121

## Actual Behavior ##

```
--- FAIL: rhcos.linux.nfs.v4 (167.07s)
        nfs.go:76: NFS server booted.
        nfs.go:81: Test file "/tmp/tmp.G04yeAUFem" created on server.
        nfs.go:118: NFS client booted.
        nfs.go:131: var-mnt.mount status is "unknown": Process exited with status 3
```

```
systemctl status var-mnt.mount
● var-mnt.mount - NFS Client
   Loaded: loaded (/etc/systemd/system/var-mnt.mount; disabled; vendor preset: enabled)
   Active: inactive (dead)
    Where: /var/mnt
     What: 172.31.18.42:/
```

## Other Information ##
Raising issue here as suggested by @arithx. Original mantle issue: https://github.com/coreos/mantle/issues/905

The detailed logs can be found here: https://continuous-infra-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/rhcos/job/jerzhang-test-coreos-rhcos-aws-test-and-launch/6/ , under build artifacts.

**Comment by ajeddeloh** [comment]
I'm inclined to think this is not an Ignition bug, it looks like Ignition is writing out the right unit (can you `systemctl cat` the unit?). Tip: add a `platform.Manhole(m)` to the test to drop into a shell and debug. See if you can get the nfs mounted at all.

**Comment by yuqi-zhang** [comment]
The issue seems to be that neither `nfs-server.service` on m1 nor `var-mnt.mount` were started by default. I can get the mount to work (and the test to pass) if I manually start both on the machines.

**Comment by ajeddeloh** [comment]
Is the service called `nfs-server.service` or is that an alias? Ignition can't enable aliases.

**Comment by yuqi-zhang** [comment]
It is just called nfs-server.service and is not a symlink:
```
-rw-r--r--. 2 root root 1010 Jan  1  1970 nfs-server.service
lrwxrwxrwx. 2 root root   18 Aug 26 00:10 nfs.service -> nfs-server.service
```

The full test is at: https://github.com/coreos/mantle/blob/master/kola/tests/misc/nfs.go and was passing last week (hasn't been changed), so I suspected some change in the updated AWS image was causing the issue.

**Comment by arithx** [comment]
It looks like the systemd-preset created by Ignition isn't being ran after digging into it a bit.

**Comment by ajeddeloh** [comment]
Closing this, since Ignition is creating the preset file.
