### ISSUE TITLE
Ignition follows absolute symlinks

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/ignition#640]
# Bug #

## Operating System Version ##
Any

## Ignition Version ##
v0.28.0

## Environment ##
What hardware/cloud provider/hypervisor is being used to run Ignition?
Any

## Expected Behavior ##
Ignition either refuses to follow absolute symlinks or follows them as if it were rooted in the filesystem the link is in.

## Actual Behavior ##
Ignition follows absolute symlinks with the initramfs root as /

## Reproduction Steps ##
Boot with this config:
```
{
  "ignition": { "version": "2.2.0" },
  "storage": {
    "links": [{
      "filesystem": "root",
      "path": "/var/bar",
      "target": "/etc"
    },
    {
      "filesystem": "root",
      "path": "/var/bar/baz",
      "target": "/foo/bar"
    },
    ]
  }
}
```
Observe that no symlink to `/foo/bar` named `baz` exists in `/etc`

## Other Information ##
Ignition should either fail if it tries to follow an absolute symlink or follow them as if they are rooted in the filesystem it is operating on.

**Comment by jlebon** [comment]
Ahhh yes, the good ol' relative absolute symlink issue. This is something that has come up multiple times elsewhere. Most recently: https://github.com/openshift/machine-config-operator/pull/17#discussion_r211956884 and https://github.com/projectatomic/rpm-ostree/pull/1481. In the latter, we just do the equivalent of what here would be `chroot /sysroot realpath ...` to resolve the symlink. Not that you can't write a careful `realpath_within_rootfs()` style function (I had initially written one in https://github.com/projectatomic/rpm-ostree/pull/410/), but if one can, it's way simpler to just `chroot`.

**Comment by cgwalters** [comment]
https://lwn.net/Articles/767547/ is hopefully coming.
