### ISSUE TITLE
Consider not using absolute paths for helper utilities

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/ignition#648]
# Feature Request #

## Environment ##
Any

## Desired Feature ##
Instead of using the paths hardcoded in `distro.go`, just rely on the `PATH` environment variable.

## Other Information ##
This would make building Ignition for other distros easier and drop some code.

Main disadvantage I see is that right now all of our deps are listed in one place, but that could be replaced with something that's just a bunch of constants.

**Comment by bgilbert** [comment]
We could keep the distro override functionality but set the defaults to relative paths.

**Comment by ajeddeloh** [comment]
Is that a use case that would be helpful? Distros could just modify the PATH in the initramfs to include the right thing if they want to do something special.

**Comment by bgilbert** [comment]
Yeah, I guess not.

**Comment by ajeddeloh** [comment]
Actually I've come around to your point of view. Binary names might change across distros. A good example that Ignition doesn't use is gpg and gpg2. On the other hand that's rare enough it may not be worth it. There's still value in keeping all the commands listed in the same place and that would make patching it for distros that do non-standard things easy.
