### ISSUE TITLE
GCE provides automation scripts by metadata.startup-script

### ISSUE THREAD

**Issue by Trane9991** [coreos/ignition#654]
# Bug #

When CoreOS create instance with Google Cloud Console or Terraform automation script will be placed in `metadata.startup-script` while Ignition checks for the `metadata.user-data`. Even if [documentation](https://coreos.com/os/docs/latest/booting-on-google-compute-engine.html) describes that ignition config should be placed under custom key `metadata.user-data` it is still very confusing because GCE and Terraform documentation suggests default `metadata.startup-script` as well as GCE Console Automation text field.

## Ignition Version ##

CoreOS stable 1855.5.0
amd64-usr published on 2018-10-24

## Environment ##

GCE

## Expected Behavior ##

Ignition gets the user data from the default `metadata.startup-script`

## Actual Behavior ##

Ignition gets the user data from the `metadata.user-data`

## Reproduction Steps ##

Create GCEinstance with next Terraform resource:
```
resource "google_compute_instance" "coreos-host" {
  name         = "coreos-host"
  machine_type = "f1-micro"
  zone         = "us-central1-a"

  boot_disk {
    initialize_params {
      image = "family/coreos-stable"
      size = 10
      type = "pd-standard"
    }
  }

  network_interface {
    network = "default"

    access_config {
        network_tier = "STANDARD"
    }
  }

  metadata_startup_script = "${file("./startup.ign")}"

  service_account {
    scopes = ["userinfo-email", "compute-ro", "storage-ro"]
  }
  allow_stopping_for_update = true
}
```

## Other Information ##
For backward compatibility, ignition could check both keys.

**Comment by ajeddeloh** [comment]
I don't know how I feel about this. An Ignition config is very much not a script. Terraform should be setting `metadata.user-data`. [example](https://github.com/coreos/tectonic-installer/blob/0ec6b27c6d4ba56f03eef6425f52292aec20cb1c/modules/gcp/etcd/etcd.tf#L43)

Looks like cloudinit also uses `user-data`: https://cloudinit.readthedocs.io/en/latest/topics/datasources/gce.html

**Comment by lucab** [comment]
Thanks for the report. However I believe that the current behavior of Ignition and coreos.com docs are correct as-is.

In particular, Ignition consumes a JSON-based declarative configuration as user-data (via `metadata.user-data`). Instead, `metadata.startup-script` has very different semantics based on imperative scripting (and described in [GCP docs](https://cloud.google.com/compute/docs/startupscript)).
As such, the two fields are in fact *not* equivalent and Ignition is not supposed to consume and run scripts coming from the latter.

If you are looking at how to model that via Terraform, please note that the "google" provider supports it via https://www.terraform.io/docs/providers/google/r/compute_project_metadata.html
An example of that in action is in the old Tectonic installer: https://github.com/coreos/tectonic-installer/blob/0ec6b27c6d4ba56f03eef6425f52292aec20cb1c/modules/gcp/etcd/etcd.tf#L43

**Comment by Trane9991** [comment]
Yep, that's true, I was able to make it work providing custom `user-data` key to metadata, however, my intention is to try to reduce the frustration that I faced trying to make it work (this issue itself will work as one more reference to the documentation).

Maybe some collaboration with GCP documentation is possible?
Would be nice to add some reference about CoreOS on the [Startup Script documentation page](https://cloud.google.com/compute/docs/startupscript), since it was the first place where I went looking when `metadata.startup-script` didn't work for me. Thanks.

**Comment by lucab** [comment]
@Trane9991 good to hear.

Please note that startup/shutdown script are completely unrelated to CoreOS or Ignition. Instead you can maybe open a support ticket via your GCP channel to ask for a quick Ignition mention where they describe cloud-init usage: https://cloud.google.com/container-optimized-os/docs/how-to/create-configure-instance

From our side, docs already mentions where Ignition sources its configuration: https://coreos.com/ignition/docs/latest/supported-platforms.html

**Comment by sampcoug** [comment]
Hello,

I am using Terraform to launch the GCE VM instance and have added the metadata piece as startup script automation to my terraform code : 

>       metadata {
        startup-script = <<SCRIPT
        #!/bin/bash
        sudo su
        echo "this is a test" > /var/log/test.txt

 
The metadata script doesn't seem to run at all. I tried without "sudo su" and that didn't work either. 
However, I do see the script was added to the - Custom metadata section. I am using the 

> coreos-stable-1911-4-0-v20181127

Any idea folks?

**Comment by ajeddeloh** [comment]
That's a different issue. It's probably best to open a bug at `https://github.com/coreos/bugs/`. Container linux only uses the userdata field and ignores all other GCE fields. Using startup scripts of cloudinit is discouraged. Far better to write a systemd unit to do what you want and add it via Ignition. This ensures you know where in the boot process it runs and get all of systemd's niceties like having other units depend on it.

**Comment by sampcoug** [comment]
Thanks Andrew! My reason for using metadata was to automate the docker pull/run on the VM. I tried using systemd, created service as below:

`- name: fakename.service
      enabled: true
      command: start
      contents: |
        [Unit]
        Description=nothing to do

        [Service]
        User=core
        TimeoutStartSec=0
        Restart=on-failure
        RestartSec=30s`
     `ExecStartPre=-/usr/bin/docker volume create shared
        ExecStartPre=gsutil cp gs://xx/keyfile.json .
        ExecStartPre=cat keyfile.json | docker login -u _json_key --password-stdin https://us.gcr.io
        ExecStartPre=-/usr/bin/docker kill ${shortname}
        ExecStartPre=-/usr/bin/docker rm -f ${shortname}
        ExecStartPre=/usr/bin/docker pull ${docker_repo}
        ExecStart=/usr/bin/docker run --name ${shortname} \
                                     -e "HOST_LOG_PATH=/var/log/rw_host/xx" \
                                      -v shared:/var/log/xx/xx \
                                      -v /var/log/rw:/var/log/xx\
                                      -v /var/log/nginx:/var/log/xx \
                                      --network=host ${docker_repo}`

It didn't work either. I had the same process working in AWS. Like you mentioned, I will open a bug with - `https://github.com/coreos/bugs/`.

**Comment by ajeddeloh** [comment]
Closing this bug since it looks like this was discussed in https://github.com/coreos/bugs/issues/2558.
