### ISSUE TITLE
Consider splitting config into seperate repo

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/ignition#658]
# Feature Request #

## Environment ##
All

## Desired Feature ##
Consider separating the Ignition config from the rest of the Ignition sources. The config and Ignition are largely decoupled and many projects (e.g. matchbox, ct) depend on just the config. Splitting it would make the config easier to consume and vendor by other projects. This would reduce conflicts when vendoring since projects consuming only the config wouldn't pickup the deps for applying a config.

What would fall under the config:
* The ignition schema json
* Generated go structs from the json
* Validation code
* Documentation on the spec
* Translation code
* Appending code

What would fall under Ignition
 * Code for fetching configs, logic for what to append to what
 * Code for applying the config
 * Docs not relating to the spec
 * Links to spec's docs

This would also make https://github.com/coreos/ignition/issues/599 easier.

Obvious cons include more churn with regards to updating dependencies.

An open question is how would the spec be versioned for minor changes to validation? We could make the patch field from semver also imply "no change to the structs/schema, only validation and other misc changes". Ignition would then essentially ignore the patch version. We could also keep master always in a good state and just vendor that directly.

cc @dustymabe for packaging implications with rpms
cc @abrarshivani for related issue
cc @bgilbert for general feedback and thoughts on versioning

**Comment by dustymabe** [comment]
> cc @dustymabe for packaging implications with rpms

Would things be versioned differently? Would we vendor the config into ignition? Either way I think we can make it work from a packaging perspective. We already pull from two upstream locations for the ignition rpm today, so it probably would be ok.

**Comment by ajeddeloh** [comment]
> Would things be versioned differently?

Yes, pending thoughts from @bgilbert. Or it could be left unversioned.

> Would we vendor the config into ignition?

Yes. We want to keep the Ignition repo "ready to compile"

**Comment by bgilbert** [comment]
It's not obvious to me that the change is worth the complexity, at least for now, but I also haven't really had firsthand experience with the vendoring pain.

I don't think the _spec_ should be versioned for minor validation changes.  If we have a 3.0.0 and a 3.0.1 spec, we're unlikely to provide the old validation behavior if spec 3.0.0 is requested.  It would make sense to version the config codebase though.

**Comment by ajeddeloh** [comment]
I think I'm inclined to agree here.
