### ISSUE TITLE
Drop support for platform default configs

### ISSUE THREAD

**Issue by bgilbert** [coreos/ignition#668]
# Feature Request #

## Environment ##

Any

## Desired Feature ##

Consider dropping support for `default.ign` files in spec 3.0.  In Container Linux they're only used for enabling coreos-cloudinit.

**Comment by ajeddeloh** [comment]
SGTM

**Comment by bgilbert** [comment]
With #675 done, there's no reason to keep these around.

**Comment by rfairley** [comment]
I can take a look into this one!
