### ISSUE TITLE
Consider dropping script, cloudinit detection in spec 3.0.0

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/ignition#675]
# Feature Request #

## Desired Feature ##

Ignition currently detects when cloudinit or shell scripts are passed in via userdata instead of an Ignition config. This is important for CL since either could be handed to it. With *COS Ignition configs are the only accepted input and this detection can be dropped.

## Other Information ##

To play devil's advocate, we could still detect them and just error out with a helpful message.

**Comment by bgilbert** [comment]
This (and #668) assumes no other Ignition-using distros will want to conditionally enable cloud-init.

**Comment by bgilbert** [comment]
This was done in https://github.com/coreos/ignition/pull/697.  Should we close?

**Comment by ajeddeloh** [comment]
Yup
