### ISSUE TITLE
Extra blackbox tests being generated

### ISSUE THREAD

**Issue by arithx** [coreos/ignition#685]
# Bug #

## Ignition Version ##

Current master

## Expected Behavior ##
Certain tests have an additional generated test with a test name like `Example_Test_Name_` without a version present, it seems like the version being used is the MinTestVersion specified by the test. Without digging further it almost looks like we're essentially duplicating the base test itself without specifying the version number.

## Actual Behavior ##
Tests without the version number at the end are not created

**Comment by ajeddeloh** [comment]
Looks like some are just missing configMinVersion. Fixing.

**Comment by ajeddeloh** [comment]
Closed via https://github.com/coreos/ignition/pull/687
