### ISSUE TITLE
Update migration docs for 3.0.0

### ISSUE THREAD

**Issue by arithx** [coreos/ignition#705]
# Feature Request #

## Desired Feature ##

The migration docs should be updated for spec 3.0.0.

This will include things like including new sections for how to write networkd configs & dropins from the files section.

Initial list of new sections based off of current features:

* [x] networkd configs from files section
* [x] new filesystems semantics
* [ ] removed oem partition support

**Comment by bgilbert** [comment]
Migration docs have existed for a while now.  The lack of OEM partition support isn't mentioned, but the `oem` scheme wasn't mentioned in the 2.x specs either, so I think that's okay.  Closing.
