### ISSUE TITLE
Support GCS urls for ignition?

### ISSUE THREAD

**Issue by smarterclayton** [coreos/ignition#707]
# Feature Request #

I was trying to boot RHCoS instances on GCS for use with OpenShift and naively expected ignition to support GCS ignition URLs like S3 ignition URLs are supported.

Set `user-data` to `gcs://<bucket>/bootstrap.ign`, expected boot, got

```
[  203.077941] ignition[4358]: DEBUG    : parsing config: {"ignition":{"config":{"replace":{"source":"gcs://clayton-test-1-ignition-bootstrap.ign/bootstrap.ign","verification":{}}},"timeouts":{},"version":"2.1.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}
[  203.078018] ignition[4358]: CRITICAL : error at line 1, column 102
[  203.078083] ignition[4358]: 1: {"ignition":{"config":{"replace":{"source":"gcs://clayton-test-1-ignition-bootstrap.ign/bootstrap.ign"
[  203.078148] ignition[4358]: ^
[  203.078212] ignition[4358]: invalid url scheme
[  203.078285] ignition[4358]: WARNING  : failed to fetch config: config is not valid
[  203.078354] ignition[4358]: CRITICAL : failed to acquire config: config is not valid
[  203.078420] ignition[4358]: CRITICAL : Ignition failed: config is not valid
```

then looked and realized ignition doesn't support GCS.  This is a request that if reasonable ignition support GCS source locations to make instance level permissions to the bucket easy for booting from private buckets.

## Environment ##

What hardware/cloud provider/hypervisor is being used to run Ignition?

Google Compute Platform

**Comment by ajeddeloh** [comment]
:+1: This seems like a good idea.

How high a priority is this? Is this wanted for spec 2.x or will 3.x be fine? Current guestimate for 3.x alpha is end of feb (although that's fairly aggressive).

**Comment by smarterclayton** [comment]
Not high priority.  Other GCP enablement (dealing with forwarded ips, a few other things) are much higher.

Because GCP's metadata limit is 256KB I ended up being able to put the entire bootstrap ignition in, so this is more of a passing "would be nice maybe" instead of a "need".  256KB should be enough for anyone.
