### ISSUE TITLE
[question] Rollback ignition to last working config

### ISSUE THREAD

**Issue by tw3rp** [coreos/ignition#717]
Hi,

I was wondering if there is a way I can include multiple sources of ignition configs, and have it reboot with the touching 
`touch /boot/coreos/first_boot`

For example,
```
    "ignition": {
      "config": {
        "append": [
          {
            "source": "https://source1.com/config.json",
            "verification": {}
          },
          {
            "source": "https://source2.com/fallback.json",
            "verification": {}
          }
        ]
      }
```
and have it restart with the first boot have on. I can do this at a cloud provider level, but can I do it with coreos primitives?

Thanks,
Rahul

**Comment by ajeddeloh** [comment]
You can do hacky things like writing out a systemd unit with `ConditionFirstBoot`. What is the problem you're trying to solve? Ignition was designed to only run once and running it more than once isn't supported in a real way.

**Comment by ajeddeloh** [comment]
I'm closing this as running Ignition more than once is not supported*, but feel free to continue to ask questions here if you still have questions.

*We somewhat support the "rootless PXE" case where Ignition runs on a "fresh" filesystem every time.
