### ISSUE TITLE
Add a way to delete users/groups

### ISSUE THREAD

**Issue by bgilbert** [coreos/ignition#738]
# Feature Request #

## Environment ##

Any

## Desired Feature ##

Add a `shouldExist` attribute for users and groups, allowing the removal of an existing user/group.

## Other Information ##

This would allow the OS to ship with a default user (`core`, `fedora`, etc.) that can be removed by an Ignition config if desired.

I don't think this functionality is critical for 3.0.

**Comment by cgwalters** [comment]
The *only* user we really ship with by default that system administrators should be removing (IMO) is `core`.  We'd have to have a stronger debate about "system" users like `zincati`.

I also remember we had a debate about this in the past where I was arguing that if the sysadmin provides anything in `users`, we should omit the default `core` user.
