### ISSUE TITLE
Rework config merging

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/ignition#741]
# Feature Request #

## Desired Feature ##

Ignition config merging should be reworked to ensure:
0) These rules should be double checked to ensure they are in fact the behavior we want
1) All entries in lists have a primary key that can be used to deduplicate the lists
2) Child configs should merge structs (replace fields in the parent struct where the child specified the field)
3) When deduplicating lists, child configs should merge entries with the same primary key instead of appending
4) The spec should be audited to ensure there's no structs that would be problematic to merge in this manner.

## Other Information ##
Partially covered by but it's better to have an explicit issue
 - https://github.com/coreos/ignition/issues/719
 - https://github.com/coreos/ignition/issues/608

**Comment by dustymabe** [comment]
considering https://github.com/coreos/ignition/pull/766 merged, is this done now?

**Comment by ajeddeloh** [comment]
Yup!
