### ISSUE TITLE
Adding users ends up with unlabeled /etc/subuid

### ISSUE THREAD

**Issue by cgwalters** [coreos/ignition#762]
In FCOS today if we add a user in Ignition we end up with `/etc/subuid` (and `/etc/subgid`) being `unlabeled_t`.  We need to add those files to our list of things that get relabeled if a user is added.

**Comment by jlebon** [comment]
Opened #764 for this. How did you find this BTW, did you see a denial in the logs? Just gauging whether we should backport this to `spec2x` right away.

**Comment by cgwalters** [comment]
> How did you find this BTW, did you see a denial in the logs?

So while I was on a long adventure debugging `core` user differences between fcos/rhcos, at one point I hacked up the `run` command to auto-login the `root` user.  Then I noticed `coreos-useradd-core.service` was failing due to this SELinux denial.
