### ISSUE TITLE
Ignition not pulling remote File

### ISSUE THREAD

**Issue by Flyffies** [coreos/ignition#785]
# Bug #

Hi, I read in the ducumentation about the possibility to let the ignition File specify a remote location to download a file from, but I cant seem to get it to work  and start to thing it might be a bug.

## Operating System Version ##
Docker 18.09
## Ignition Version ##
2.2.0
## Environment ##

Matchbox in a docker container. 
Is connected to the Internet and can reach the tested hosts.

## Expected Behavior ##

Response from "curl <host:port>/ignition to contain something in the files contents.

## Actual Behavior ##

The json "contents" section contains an empty data uri.

## Reproduction Steps ##

  1. ? no clue

## Other Information ##

ignition.json
```
{
  "ignition": {
    "version": "2.3.0"
  },
  "storage": {
    "files": [
      {
        "filesystem": "root",
        "path": "/test-web.html",
        "mode": 775,
        "contents": {
          "source": "https://httpbin.org/uuid"
        }
      }
    ]
  }
}
```

curl response:
```
{
  "ignition": {
    "config": {},
    "security": {
      "tls": {}
    },
    "timeouts": {},
    "version": "2.2.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {
    "files": [
      {
        "filesystem": "root",
        "path": "/test-web.html",
        "contents": {
          "source": "data:,",
          "verification": {}
        },
        "mode": 775
      }
    ]
  },
  "systemd": {}
}
```

**Comment by ajeddeloh** [comment]
Sounds like this is a matchbox bug. Is matchbox expecting a CLC instead of an Ignition config?

**Comment by Flyffies** [comment]
How do mean that exactly?

Ohh or maybe I figured it out... You mean the code that rendered the template is not in this repo, but in the matchbox one?

**Comment by ajeddeloh** [comment]
Right. I *think* matchbox uses [CLCs](https://coreos.com/os/docs/latest/provisioning.html) which are more human friendly and get transpiled to Ignition configs. The structure in `files` is slightly different which I think is why the contents of the source are being dropped.

**Comment by ajeddeloh** [comment]
Closing since this looks like either matchbox needs to be handed a CLC or it's a matchbox issue.
