### ISSUE TITLE
Ignition runs on every boot

### ISSUE THREAD

**Issue by crawford** [coreos/ignition#79]
When Ignition runs the disks target, systemd cannot check /etc/machine-id because root isn't mounted yet. As a result, it attempts to run the stage on every boot.

**Comment by vcaputo** [comment]
We have limited options for persisting the "has booted" state outside of the root fs.  GPT? EFI variables?

Maybe take a different approach, only run ignition if /proc/cmdline says to run it, then have whatever initiates the first boot set the flag just like one informs ignition of which config provider to use?

**Comment by crawford** [comment]
I don't think we need to represent it outside of the root fs. In fact, I think it's very advantageous to have it in the root fs (you can `rm -rf /` and it will create a brand new machine for you). I think we should just attempt to mount / to check for the file and then unmount.

**Comment by crawford** [comment]
We've decided to check the disk UUID to determine if the machine has booted before.

```
ConditionPathExists=/dev/disk/by-uuid/00000000-0000-0000-0000-000000000001
```

**Comment by vcaputo** [comment]
Correct, we'll randomize the *disk* GUID once ignition runs successfully.

Note that udev doesn't currently create `/dev/disk/by-uuid/` links for the disk GUID, but we can add that and just watch for the special path.

`sgdisk --disk-guid=R /path/to/disk` can be used for randomizing the GUID on successful ignition.

Someone can then explicitly rewrite the disk GUID to `00000000-0000-0000-0000-000000000001` and reboot for a reinitialization.

I like this much more than the absent `/etc/machine-id` trigger.
