### ISSUE TITLE
Set dns for ignition fetches

### ISSUE THREAD

**Issue by rgolangh** [coreos/ignition#806]
# Feature Request #
I want to be able to tweak network settings prior to an attept to fetch a remote config

What hardware/cloud provider/hypervisor is being used to run Ignition?
A VM from a fedora coreos image

## Desired Feature ##
The ignition config for this VM says "append: some.url" but the machine can't resolve it.
I could try to pass a kernel parameter like 'nameserver=", but it would be more powerful 
to specify that in ignition config.

**Comment by bgilbert** [comment]
Could you talk more about why this is needed?  Do you have a static network configuration?  Are you using DHCP but the DHCP-provided nameservers are incorrect?

**Comment by rgolangh** [comment]
I'm working on https://github.com/openshift/installer, and my baremetals are VMs. In short this installer moto is to create all the openshift infrastructure needed by creating several VMs, where one of the acts as a temporary DNS server and ignition config server. Other booting VMs will pull their ignition config from it, and that is why I need to prepend the nameserver to the rest if the booting VMs.

**Comment by bgilbert** [comment]
By design, Ignition only affects configuration (including network configuration) in the real root, not in the initramfs.  So it can't affect its own ability to fetch things.  It sounds as though in your case you could hardcode the IP address of the Ignition config server in the append directive?

**Comment by rgolangh** [comment]
Indeed, but then it will fail to verify ssl. Well the nameserver is also an IP in the end...

**Comment by ajeddeloh** [comment]
@bgilbert well kind of. Ignition can modify how it fetches things, just not affect the initramfs as a whole (see: ca certs, proxies).

I'm not sure if you can set the dns golang uses on the fly. I'm not opposed to changing it on the fly with a section under the `ignition` section, but that would need to go in spec `2.4.0-experimental` or `3.1.0-experimental` (depending on which branch it goes in). This would mean switching openshift over from 2.2.0 to 2.4.0-experimental.

These certs are generated, yes? Could you generate the certs twice? Once for Ignition with an ip and once for the real root with the domain name. The `ignition.security.tls.cas` section is only for ignition's use, so the certs there don't need to match and wont affect the certs in the real root.

**Comment by ajeddeloh** [comment]
If I understand correctly that would affect the whole initramfs not just Ignition. There may be other things running in the initramfs using networking that this would mess with. Currently Ignition is the only thing there using it, but in the future it may not be.

**Comment by e-minguez** [comment]
> In the end I added to the cert the IP address, under the alt_name attribute, which I think is a valid thing to do and it works without any further modifications.

I'm having the same issue. Do you mind to share the steps you did? I believe the process will be to extract the tls.crt from the manifests/machine-config-server-tls-secret.yaml file (tls.crt secret) and recreate it with the IP as alt_name.

Thanks.

**Comment by rgolangh** [comment]
Yes look here https://github.com/rgolangh/installer/commit/69f973204473e567aa599066228b7751df745c91#diff-9a45bee38dc4a16df1b60c1d018a61e1R44

**Comment by ajeddeloh** [comment]
What's the status on this? Is there still a hard need for it? I'm going to close this unless it's unavoidable.

**Comment by rgolangh** [comment]
It is avoidable, by trusting the IP in the cert like mentioned above.

@ajeddeloh I think the use case still remains relevant but I'll close this since there is no other demand for it. Thanks.
