### ISSUE TITLE
Enable reading ignition config by z/VM hypervisor

### ISSUE THREAD

**Issue by zhengxiaomei123** [coreos/ignition#810]
# Feature Request #
We would like to deploy coreos instances in openstack platform with z/VM hypervisor. Because of the z/VM limitation, the custom instance can only get their userdata by configdrive. And there is a tool to help get configdrive iso in z/VM. Is there any suggestion to make ignition get the ignition config by config-drive in z/VM hypervisor?
## Environment ##
z/VM hypervisor on OpenStack platform

## Desired Feature ##
Ignition can get config by configdrive in z/VM
## Other Information ##
About the z/VM hypervisor, https://docs.openstack.org/nova/latest/admin/configuration/hypervisor-zvm.html

**Comment by ajeddeloh** [comment]
The `openstack` provider should read from the config drive. What images are you using? Does z/VM put the user data in a different place than "normal" openstack?

**Comment by zhengxiaomei123** [comment]
@ajeddeloh Hi , we use the fedora cores qcow2 image to do the experiment. z/VM transfer the userdata with reader(A Shared virtual storage device with access control permissions). It is different from the common openstack and we use the specific tool to read the userdata in reader and then the cloud-init can use it to config the instance.

**Comment by ajeddeloh** [comment]
Ah gotcha, sorry, was assuming Container Linux. I assume you're using the openstack qcow2 not the qemu one? Do you have documentation describing what needs to be done to fetch the config and/or what that specific tool is doing?

**Comment by zhengxiaomei123** [comment]
Yes, we use the openstack.qcow2.

**Comment by zhengxiaomei123** [comment]
@ajeddeloh I will try to explain How to use cloud-init to customize the z/VM virtual machine and what that specific tool is doing?

**Comment by zhengxiaomei123** [comment]
The virtual machines deployed on the zVM only support Cloud-init to read metadata from the config-drive.
Image customization for zVM virtual machines is different from other platforms due to the special architecture of zVM, which cannot create an iso9660 loop device directly  attaching to the virtual machine on the hypervisor like libvirt.

zVM virtual machine requires an additional active engine (We call it zvm_guest_configure[1] ) to  cooperate with cloud-init to customize the virtual machine. The zvm_guest_configure is mainly developed to adapt to the particularity of zVM platform. It makes some preparations for the operation of Cloud-init on the zVM virtual machine. It needs to run before all the services of Cloud-init.

When a virtual machine is deployed through openstack, nova-zvm-driver generates a cfgdrive.tgz file of metadata used to customize the virtual machine, and then punches this TGZ file onto the Reader device of the ZVM's target virtual machine.

When the virtual machine starts up, zvm_guest_configure will download the cfgdrive.tgz file from the Reader, and then generate an iso9660 loop device by 'mkisofs', so that Cloud-init can correctly find the loop device and then automatically mount it to get the virtual machine's metadata information.

Ignition will choose where to look for configuration based on the underlying platform.
The underlying platform for us is OpenStack and z/VM hypervisor, with the cloud init tool is zvm_guest_configure and Cloud-init. In the initramfs process, we just need to make zvm_guest_configure or other service process the config_drive.iso file that punched by openstack nova-zvm-driver for Ignition and Cloud-init working . The other script file or sh file can be processed in the user space before the Cloud-init process.

[1]https://github.com/mfcloud/python-zvm-sdk/blob/master/tools/share/zvmguestconfigure

**Comment by ajeddeloh** [comment]
To make sure I'm understanding correctly: the hypervisor adds the config to the guest via some kind of reader device, then a service converts that into a config drive that cloudinit uses?

Assuming that's the case, I'd much rather have Ignition read from the reader device directly instead of converting it to a iso image then using that. Is that interface stable? We try to keep Ignition's dependencies on the system minimal and not platform specific, so requiring special platform specific tools in the initramfs is not ideal.

**Comment by zhengxiaomei123** [comment]
> When a virtual machine is deployed through openstack, nova-zvm-driver generates a cfgdrive.tgz file of metadata used to customize the virtual machine, and then punches this TGZ file onto the Reader device of the ZVM's target virtual machine.
> 
> When the virtual machine starts up, zvm_guest_configure will download the cfgdrive.tgz file from the Reader, and then generate an iso9660 loop device by 'mkisofs', so that Cloud-init can correctly find the loop device and then automatically mount it to get the virtual machine's metadata information.
> 
@ajeddeloh I have an update here. When a virtual machine is  deployed through openstack, nova-zvm-driver convert user-data to a iso file and punch the iso to reader device.

**Comment by zhengxiaomei123** [comment]
> To make sure I'm understanding correctly: the hypervisor adds the config to the guest via some kind of reader device, then a service converts that into a config drive that cloudinit uses?
That's not the case, the hypervisor adds the iso config file to the guest via some kind of reader device, then a service make the reader device online and read iso config file from the reader. The converting process is not needed anymore , but we still need to do the "losetup" to setup the iso file to a loop device.
> Assuming that's the case, I'd much rather have Ignition read from the reader device directly instead of converting it to a iso image then using that. Is that interface stable? We try to keep Ignition's dependencies on the system minimal and not platform specific, so requiring special platform specific tools in the initramfs is not ideal.
Ignition firstly make the reader device online and read from the reader device directly. but the file pulled from reader can not be used by cloud-init, we still need to set up it to a loop device. 
>  requiring special platform specific tools in the initramfs is not ideal.
I can not understand this limit, if we build the coreos-x390-qcow2 image, can we customize the initramfs?

**Comment by zhengxiaomei123** [comment]
> To make sure I'm understanding correctly: the hypervisor adds the config to the guest via some kind of reader device, then a service converts that into a config drive that cloudinit uses?
> 
That's not the case, the hypervisor adds the iso config file to the guest via some kind of reader device, then a service make the reader device online and read iso config file from the reader. The converting process is not needed anymore , but we still need to do the "losetup" to setup the iso file to a loop device.

**Comment by zhengxiaomei123** [comment]
> Assuming that's the case, I'd much rather have Ignition read from the reader device directly instead of converting it to a iso image then using that. Is that interface stable?

Ignition firstly make the reader device online and read from the reader device directly. but the file pulled from reader can not be used by cloud-init, we still need to set up it to a loop device.

**Comment by zhengxiaomei123** [comment]
> so requiring special platform specific tools in the initramfs is not ideal.

I can not understand this limit, if we build the coreos-x390-qcow2 image, can we customize the initramfs?

**Comment by ajeddeloh** [comment]
> I can not understand this limit, if we build the coreos-x390-qcow2 image, can we customize the initramfs?

For Fedora CoreOS we're shipping the same image (including initramfs) everywhere (a kernel command line option changes to specify what platform it's for, otherwise they're identical). Anything we ship for one platform we need to ship for all.

For Ignition in general we don't want to carry dependencies if we can avoid it. Implementing the absolute minimum to read the config is _strongly_ preferred. Is there any documentation on this reader device?

> @ajeddeloh I have an update here. When a virtual machine is deployed through openstack, nova-zvm-driver convert user-data to a iso file and punch the iso to reader device. Converting to iso is not needed anymore.

Would it be possible to punch through the config file directly without wrapping it in an iso at all?

Finally, I should check that there's no network based metadata server available in this case. We prefer those since device-based metadata makes it hard to differentiate between "the device hasn't shown up _yet_" and "the device is not going to show up". I understand this probably isn't the case but want to be sure.

**Comment by zhengxiaomei123** [comment]
> Would it be possible to punch through the config file directly without wrapping it in an iso at all?
> 

I got it. We would like to try punch the config.ign file directly. Ignition just read the config.ign from reader device.Not iso in ignition at all. We just need to make sure that Ignition work well(To make it, we need to deliver the ignition config to Ignition).

> Finally, I should check that there's no network based metadata server available in this case. We prefer those since device-based metadata makes it hard to differentiate between "the device hasn't shown up _yet_" and "the device is not going to show up". I understand this probably isn't the case but want to be sure.

Yes,The z/VM platform only support L2 network virtualization but metadata server need L3 network. We have to choose the device-based metadata. We can do the zvm_guest_config and cloud-init in root filesystem later If there are some configs Ignition can not do it.

**Comment by zhengxiaomei123** [comment]
> For Ignition in general we don't want to carry dependencies if we can avoid it. Implementing the absolute minimum to read the config is _strongly_ preferred. Is there any documentation on this reader device?

Make the reader device online and pull data from reader is just serval shell script .I will try to find some document to help understand it.

**Comment by lucab** [comment]
@zhengxiaomei123 for your reference, qemu hypervisor has a similar guest back-channel called [fw_cfg](https://github.com/qemu/qemu/blob/master/docs/specs/fw_cfg.txt) that Ignition is [using](https://github.com/coreos/ignition/blob/master/internal/providers/qemu/qemu.go) to directly read instance metadata. This works pretty well because it doesn't require additional special setup in the initramfs, nor waiting for a config-drive that may not show up.

If possible, we would like to aim for a similar flow for z/VM, directly consuming the content punched through the reader.

**Comment by zhengxiaomei123** [comment]
> @zhengxiaomei123 for your reference, qemu hypervisor has a similar guest back-channel called [fw_cfg](https://github.com/qemu/qemu/blob/master/docs/specs/fw_cfg.txt) that Ignition is [using](https://github.com/coreos/ignition/blob/master/internal/providers/qemu/qemu.go) to directly read instance metadata. This works pretty well because it doesn't require additional special setup in the initramfs, nor waiting for a config-drive that may not show up.
> 
> If possible, we would like to aim for a similar flow for z/VM, directly consuming the content punched through the reader.

Hi Lucab, That sounds great for us. The reader device is similar to fw_cfg. For z/VM hypervisor , the FetchConfig function includes online the reader device and pull data from reader device. All can be implemented by several shell scripts. We can contribute to it. Be the way, We are trying to build the Fedora-coreos-s390-qcow2 image, once we finished the build , we can do the test using the image.
Anything need us to do, please let me know. Thanks.

**Comment by ajeddeloh** [comment]
We want to avoid using shell scripts too. We prefer pure go implementations when possible. If that's not possible and there's a C library, we can use cgo and call into that. Failing both of those, we can fall back to converting the shell script to series of go `os.Exec` calls.

**Comment by zhengxiaomei123** [comment]
> We want to avoid using shell scripts too. We prefer pure go implementations when possible. If that's not possible and there's a C library, we can use cgo and call into that. Failing both of those, we can fall back to converting the shell script to series of go `os.Exec` calls.

I got it.
