### ISSUE TITLE
Online validation service allows arbitrary JSON

### ISSUE THREAD

**Issue by IvanBoyko** [coreos/ignition#820]
# Bug #

When using online validation service https://coreos.com/validate/  
it seems to check just JSON validity, but not against the [schema of Ignition config](https://coreos.com/os/docs/latest/configuration.html).

## Expected Behavior ##

> Config Invalid!

## Actual Behavior ##

> Validation Results:
> Your config is valid!

## Reproduction Steps ##

  1. Open in browser: https://coreos.com/validate/
  2. Use this input:
```json
{
    "asdf": 123
}
```
(which I'm sure doesn't fit the schema of Ignition config)

  3. Click "Validate Config"

## Other Information ##

I'm aware of https://github.com/coreos/container-linux-userdata-validator project,  
but it doesn't allow creating Issues there.

**Comment by lucab** [comment]
@IvanBoyko did you try with the `ignition-validate` binary, does that misvalidate it as well?

The online validator has some additional additional logic to detect old-style cloud-init configs and plain scripts, so it may get confused.

**Comment by IvanBoyko** [comment]
No, I haven't checked with the `ignition-validate` binary.  
Somehow I feel it will be alright :)
We will be switching to it for our validation scripts.
Just thought maybe someone can shed the light on the online validator... maybe I was missing something...

**Comment by lucab** [comment]
@IvanBoyko oh yes, the online validator one seems definitely a bug/quirk, and thanks for the reporting it. The `ignition-validate` binary is exactly meant for CI purposes, so it fits your usecase better. Let us know if that works, as that would help pinpointing the bug too.

**Comment by iDigz** [comment]
@lucab i try ignition-validate.
ignition-validate /mnt/test.ign 
couldn't parse config: unsupported config version

this ign file
{
  "ignition": {
    "config": {},
    "security": {
      "tls": {}
    },
    "timeouts": {},
    "version": "2.2.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {},
  "systemd": {
    "units": [
      {
        "enable": true,
        "name": "docker.service"
      }
    ]
  }
}

**Comment by lucab** [comment]
@iDigz you need a matching version to support the schema you are using. Ignition 2.0.0 only supports schemas >= 3.x.

**Comment by arithx** [comment]
@iDigz if you're downloading `ignition-validate` from the releases page make sure that you're grabbing [`v0.32.0` assets](https://github.com/coreos/ignition/releases/tag/v0.32.0). Ignition `v2.0.0` supports spec version `3.0.0` & later.

**Comment by IvanBoyko** [comment]
Many thanks for the information on compatibility between versions.
So we now stick to:
* ct - v0.9.0
* ignition-validate - v0.32.0

By the way we have wrapped both into a Docker image: https://hub.docker.com/r/softmill/coreos-config-transpiler
We use it in our GitLab pipelines for provisioning CoreOS.
Maybe it will be useful for others.

**Comment by bgilbert** [comment]
[container-linux-userdata-validator](https://github.com/coreos/container-linux-userdata-validator) only supports Ignition spec 2.x and coreos-cloudinit, both of which are deprecated.  The validator's GitHub repo has been archived and the validator shut down.  Closing.
