### ISSUE TITLE
Ignition v0.32.0 fails with runtime error - slice bounds out of range

### ISSUE THREAD

**Issue by sravanip1017** [coreos/ignition#821]
# Bug #
Ignition v0.32.0 fails with runtime error - slice bounds out of range
## Operating System Version ##
CoreOS Container Linux version 2135.4.0
## Ignition Version ##
v0.32.0

What hardware/cloud provider/hypervisor is being used to run Ignition?
VMWare vCenter

## Reproduction Steps ##
Deploy VM using ovftool with options `guestinfo.coreos.config.data` and `guestinfo.coreos.config.data.encoding` to inject ignition config on the first boot
## Other Information ##
The ignition process on first boot seems to be working fine with ignition v0.31.0 but having issues with latest version v0.32.0
Below are the logs captured at the time of boot up
<img width="1470" alt="Screen Shot 2019-06-26 at 5 01 37 PM" src="https://user-images.githubusercontent.com/21114735/60306619-b6098f00-98f5-11e9-8fa6-c898fafcefd4.png">
Screenshot below has Ignition service failure logs from journalctl
<img width="1470" alt="Screen Shot 2019-06-26 at 5 06 38 PM" src="https://user-images.githubusercontent.com/21114735/60306646-d33e5d80-98f5-11e9-87c0-2083303de06f.png">

More logs:
go panic stack trace of ignition
<img width="1331" alt="ignition_go_panic_stack_trace" src="https://user-images.githubusercontent.com/21114735/60306749-4e077880-98f6-11e9-8e8d-5831aed55a42.png">

**Comment by arithx** [comment]
It looks like this [case](https://github.com/coreos/ignition/blob/spec2x/internal/providers/vmware/vmware_amd64.go#L76-L78) in the VMware provider needs to exit with a nil config rather than continuing & the other stages can drop adding `guestinfo.` to the `ovfDataKey` & `ovfEncodingKey` rather than stripping them later.

**Comment by ajeddeloh** [comment]
Thanks for the report. I'll try to get a fix for this merged tomorrow and it can go into next weeks alpha. It's probably in master too.

**Comment by utyagi24** [comment]
We are currently blocked by this issue as we are unable to deploy the stable channel image using ignition. Is there any update when we can expect a fix for this?

**Comment by ajeddeloh** [comment]
I'm working on fix now, We'll roll out a new stable new week with the fix.

I presume, looking through the code, that this occurs with when no config is specified. As a workaround you can specify an empty config `{"ignition": {"config": {"version": "2.3.0"}}}` instead which should do nothing. I presume there's no cloud config either? If you need to enable cloud config you can instead specify this config: https://github.com/coreos/coreos-overlay/blob/master/coreos-base/oem-vmware/files/base/default.ign

**Comment by sravanip1017** [comment]
@ajeddeloh In this case, we are specifying the ignition config. Here is a sample of what we have in ignition config file
```
{
	"ignition": {
		"version": "2.0.0"
	},
	"passwd": {
		"users": [{
			"name": "testuser",
			"create": {
				"uid": 1000,
				"homeDir": "/home/testuser",
				"groups": [
					"sudo",
					"docker"
				],
				"shell": "/bin/bash" 
			},
                        "passwordHash": "xxxxxxxxx"
		}]
	},
        "networkd": {
    		"units": [
     		 {
        		"name": "static.network",
                        "contents": "[Match]\nName=ens*\n\n[Network]\nAddress=x.x.x.x"
      }
    ]
  }

}
```
Please note that we are using `guest:coreos.config.data` instead of `guestinfo.coreos.config.data` to specify encoded ignition config as `guestinfo.coreos.config.data` doesn't work. Ovftool throws the following error
```
Error: Unknown option: 'X:guestinfo.coreos.config.data'
Completed with errors
```
(This issue was reported [here](https://github.com/coreos/bugs/issues/1627))

**Comment by ajeddeloh** [comment]
Fix is in https://github.com/coreos/ignition/pull/822. Working on building that in a test image to confirm it works. It should restore the old behavior.

**Comment by ajeddeloh** [comment]
Closed via https://github.com/coreos/ignition/pull/822 and https://github.com/coreos/coreos-overlay/pull/3702. We will roll out the fix on all channels next week
