### ISSUE TITLE
ignition -> config -> replace not working on Digitalocean

### ISSUE THREAD

**Issue by aidun** [coreos/ignition#829]
# Bug #
I use the following ignition string as user data for a Digitalocean droplet:
`
{
  "ignition": {
    "version": "2.2.0",
    "config": {
      "replace": {
        "source": "http://${digitalocean_droplet.bootstrap-helper.ipv4_address}:80/bootstrap.ign"
      }
    }
  }
}
`
The droplet boot up, get the initial user-data and try to fetch the remote config. This not working at the moment. 

## Operating System Version ##
Droplet images coreos-{stable,beta,alpha}

## Ignition Version ##
2.2.0

## Environment ##
Digitalocean

## Expected Behavior ##
Coreos should fetch the ignition file from the http url

## Actual Behavior ##
the http client produces get error

## Reproduction Steps ##

  1. Create a do droplet with core os image
  2. Put the ignition config above as userdata
  3. Boot the droplet

## Other Information ##
I think the network connection is not configured at the moment of fetching the file. I seems DO does not provide the network configuration by DHCP.

**Comment by bgilbert** [comment]
On DigitalOcean, Container Linux doesn't have a publicly routable IP address when Ignition runs (https://github.com/coreos/bugs/issues/2205), so Ignition can't fetch arbitrary URLs.  We're not going to be able to fix that on Container Linux, but we hope to address the issue on Fedora CoreOS.

This isn't actually an Ignition bug -- it's the responsibility of [bootengine](https://github.com/coreos/bootengine/) on Container Linux or [ignition-dracut](https://github.com/coreos/ignition-dracut/) on Fedora CoreOS -- so I'll close.  Thanks for reporting.

**Comment by aidun** [comment]
Thanks for the clarification. I will watch at the other issues.
