### ISSUE TITLE
Log Ignition stage at startup

### ISSUE THREAD

**Issue by bgilbert** [coreos/ignition#837]
# Feature Request #

## Environment ##

All

## Desired Feature ##

Log the Ignition stage at startup.  It's logged at shutdown (`disks: disks passed`) but logging at startup would make `journalctl -t ignition` easier to read.

**Comment by ajeddeloh** [comment]
Fixed by https://github.com/coreos/ignition/pull/840 and https://github.com/coreos/ignition/pull/841

**Comment by ajeddeloh** [comment]
closed via #840 and #841
