### ISSUE TITLE
3.0 spec is missing from referenced documentation

### ISSUE THREAD

**Issue by ashcrow** [coreos/ignition#844]
# Bug #

From the project header:

`First boot installer and configuration tool https://coreos.com/ignition/docs/latest/`

https://github.com/coreos/ignition/blob/master/doc/configuration-v3_0.md exists and is used by `ignition` but is not noted on the referenced docs (EG: https://coreos.com/ignition/docs/latest/configuration-v3_0.html)

## Ignition Version ##
2.0.0+

## Expected Results ##
Either the link to https://coreos.com/ignition/docs/latest/ is replaced with the in tree docs or the coreos.com docs are updated with the current spec.

**Comment by ajeddeloh** [comment]
Missed this bug, sorry for the long delay. The coreos.com docs are for CL and related things. That site is mostly for the CL users and only updated by the CL team at this point for new CL releases.

**Comment by ashcrow** [comment]
Got it. :+1: This can be closed.
