### ISSUE TITLE
Remote file verification hash support

### ISSUE THREAD

**Issue by wranders** [coreos/ignition#855]
Currently, [SHA-512 is the only supported hash function](https://github.com/coreos/ignition/blob/master/internal/util/verification.go#L67-L74) for remote file verification. 

Many resources (in my case, Docker Compose) are only released with SHA-256 sums, making verification currently impossible without generating my own compatible sums, which kind of defeats the purpose.

Is there a reason SHA-256 was excluded? If not, would it be possible to include it?

**Comment by lucab** [comment]
Thanks for the feedback! I don't think there is an explicit reason for excluding SHA-256. The status quo is likely the results of a pragmatic choice to initially support a strong enough scheme. I think it's reasonable to support SHA-256 too. @ajeddeloh should be back next week and able to confirm/deny that soon.

@wranders do you maybe want to start assembling a PR to support SHA-256 everywhere we currently have an hash-scheme?

**Comment by wranders** [comment]
@lucab I'll get something prepared and submitted.

**Comment by ajeddeloh** [comment]
Yeah, there's no reason I can think of to not support sha256. Wasn't implemented because no one asked.

**Comment by ajeddeloh** [comment]
@wranders were you still interested in submitting a PR?

**Comment by wranders** [comment]
@ajeddeloh Yes. I'm juggling a few things at the moment, so it's not ready.
If you need to close this, I can revisit it when I have a PR ready.

**Comment by sohankunkerkar** [comment]
@wranders are you still interested in submitting a PR for this issue?
