### ISSUE TITLE
Add mount options

### ISSUE THREAD

**Issue by laenion** [coreos/ignition#872]
# Feature Request #

## Desired Feature ##
During _mount_ stage filesystems mentioned in _storage_ - _filesystems_ are always mounted using the default options. Sometimes, however, this is not sufficient.

__Examples__:
* Btrfs subvolumes: It's currently not possible to mount subvolumes, as this would require specifying the subvolume as an option
* behavioral file system options (such as `inode32` on XFS): files created from Ignition could permanently use file system features which were not intended

## Possible solution ##
Add a new optional _storage_ - _filesystems_ - _mountOptions_ attribute to the specification, similarly to the existing _options_ attribute for `mkfs`. The options would then just be appended to the mount command.

**Comment by ajeddeloh** [comment]
I don't see a reason why not. Actually this could help solve a problem @cgwalters was looking into wrt moving the rootfs (for simple cases like onto another partition or reformatting it). It would need to go into the 3.1.0-experimental spec, as 3.0.0 is currently frozen.

@cgwalters what would you think about, in the case of reformatting root, we read off the mount options from here?

**Comment by cgwalters** [comment]
Makes sense to me!

**Comment by laenion** [comment]
Implemented in #874.
