### ISSUE TITLE
Container Linux 2247.5.0 fails to boot when deployed with ignition 

### ISSUE THREAD

**Issue by utyagi24** [coreos/ignition#878]
# Bug #

## Operating System Version ##
CoreOS Container Linux 2247.5.0

## Ignition Version ##
Ignition: 0.33.0

## Environment ##
VMware ESXi 6.0 

What hardware/cloud provider/hypervisor is being used to run Ignition?
Deploy VM on VMware ESXi 6.0 using ovftool with options guestinfo.coreos.config.data and guestinfo.coreos.config.data.encoding to inject ignition config 

## Expected Behavior ##
VM should boot up successfully 
 
## Actual Behavior ##
VM fails to boot, presents emergency shell option on the VM console

## Reproduction Steps ##
Deploy VM on VMware ESXi 6.0 using ovftool with options guestinfo.coreos.config.data and guestinfo.coreos.config.data.encoding to inject ignition config 

## Other Information ##
There has been no change in our deployment script and it works with Container Linux version 2191.5.0 and earlier. Similar issue occurred with version 2135.4.0  when we opened - #821 

<img width="1680" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/12071588/67336882-ed223280-f4da-11e9-9057-ae1dca43a0a2.png">
<img width="1680" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/12071588/67336883-ed223280-f4da-11e9-9a28-b2be8b5ae428.png">
<img width="1680" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/12071588/67336886-edbac900-f4da-11e9-9b92-e9604f823a39.png">
<img width="1679" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/12071588/67336887-edbac900-f4da-11e9-8f09-63c5c05f860b.png">

**Comment by ajeddeloh** [comment]
This looks like verity is failing. Can you confirm there's no change to /usr and the there are only 1 USR-A, USB-B and EFI-SYSTEM partitions available on the system.

**Comment by utyagi24** [comment]
We are deploying the unmodified OVA file as dowloaded from https://stable.release.core-os.net/amd64-usr/current/  
It deploys and boots up fine if deployed without ignition config, but fails to boot when deployed with ignition.

**Comment by bgilbert** [comment]
Can you post your Ignition config, or a sanitized version of it?

**Comment by ajeddeloh** [comment]
Can you verify you config passes validation with the [ignition-validate](https://github.com/coreos/ignition/releases/tag/v0.33.0) tool as well?

**Comment by utyagi24** [comment]
@ajeddeloh - I validated the config using the tool link you provided. Also, as I mentioned we have been using this config successfully for long time now - 
here is the sanitized version of the config - 
`{
  "ignition": {
    "version": "2.0.0"
  },
  "passwd": {
    "users": [{
      "name": "REDACTED",
      "create": {
        "uid": 1000,
        "homeDir": "REDACTED",
        "groups": ["sudo", "docker"],
        "shell": "/bin/bash"
      },
      "passwordHash": "REDACTED"
    }]
  },
  "networkd": {
    "units": [{
      "name": "static.network",
      "contents": "[Match]\nName=ens192\n\n[Network]\nDNS=173.36.131.10\nDNS=171.70.168.183\nAddress=10.22.162.31/25\nGateway=10.22.162.1"
    }]
  }
}`

**Comment by ajeddeloh** [comment]
Does it work with 2135.5.0? The only difference between 2135.4.0 and 2135.5.0 is the fix for the original bug, so it would be helpful to confirm that version works.

Can you get console access and run `journalctl -t ignition`?

**Comment by utyagi24** [comment]
@ajeddeloh - I can confirm that it  works with 2191.5.0, 2135.6.0 and  2135.5.0

**Comment by utyagi24** [comment]
`systemctl -t service`
<img width="1795" alt="systemctl -t service" src="https://user-images.githubusercontent.com/12071588/67518483-baeb0f00-f659-11e9-8cd1-5d3bbb45d027.png">

`systemctl --state failed`
<img width="1329" alt="systemctl --state failed" src="https://user-images.githubusercontent.com/12071588/67518530-cd654880-f659-11e9-897d-4f4d8edca617.png">

`journalctl -u verity-setup`
<img width="1795" alt="journalctl -u verity-setup" src="https://user-images.githubusercontent.com/12071588/67518568-e5d56300-f659-11e9-9d4b-2cb3e243ffe9.png">

**Comment by ajeddeloh** [comment]
That's indicating the USR-A parition is not a verity device, but it must be otherwise everyone would be hitting this. Can you run `ls /dev`?

**Comment by utyagi24** [comment]
Turns out it was a corrupted OVA download which was able to get deployed to ESXi but giving out error when booting up. Deleted the corrupted OVA file and downloaded again and it deploys fine now. Thanks @ajeddeloh for your help.
