### ISSUE TITLE
How to update firewall (iptables/ip6tables) policies via ignition

### ISSUE THREAD

**Issue by alpana17** [coreos/ignition#882]
How to update firewall (iptables/ip6tables) policies via ignition as I was not able to find anything at https://github.com/coreos/container-linux-config-transpiler/blob/master/doc/configuration.md

**Comment by ajeddeloh** [comment]
There's no specific prescribed way. I'd use the iptables-restore service and write out the rules where it expects them (which looks like `/var/lib/iptables/rules-save` judging by `systemctl cat iptables-restore`). I'm closing this as it's not really a bug.
