### ISSUE TITLE
[Docs] Add correlation between image ignition version to supported ignition specification version/s

### ISSUE THREAD

**Issue by liranr23** [coreos/ignition#894]
Currently each image of CoreOS comes with ignition version, for example v0.33.0.
The JSON file given to the ignition has it's own specification v2.2.0, v2.3.0, v3.0.0....

It would be nice if a documentation telling which versions of specification for the ignition JSON are supported in the image's ignition.

**Comment by bgilbert** [comment]
This now exists [here](https://coreos.github.io/ignition/specs/#specification-versions-and-ignition-releases).
