### ISSUE TITLE
Canonicalize the fetch stage as the only stage during which Ignition fetches configs

### ISSUE THREAD

**Issue by jlebon** [coreos/ignition#950]
Noticed this while examining the logs for a different reason. It looks like Ignition doesn't cache the fact that an Ignition config *wasn't* provided when it gets HTTP 200 with an empty body. So it ends up trying to refetch the config on each stage.

We should cache it instead (e.g. as just `{}` in `/run/ignition.json`?) and avoid  spamming the metadata server.

**Comment by jlebon** [comment]
Related: https://github.com/coreos/fedora-coreos-tracker/issues/436

**Comment by jlebon** [comment]
Also related: #903

**Comment by dustymabe** [comment]
though another question to ask is should ignition try to fetch configs in multiple stages at all? It seems like there should only be one stage that ever tries to fetch and condense an ignition config for the system. All other stages use that initial stage's output (let's say it's a written local file) as their input.

**Comment by dustymabe** [comment]
i.e. instead of solving this problem of "Ignition shouldn't try to refetch empty configs" we restate it to "Ignition should only ever try to fetch configs in one stage".

**Comment by bgilbert** [comment]
@dustymabe I think that's fair.  The current stage structure evolved over time, and now that we have a distinct fetch stage, we don't need to think of `ignition.json` as a cache anymore.

**Comment by jlebon** [comment]
Yup, agreed with the above. Keeping it to the `fetch` stage helps with solving the conditional networking issue as well.

**Comment by dustymabe** [comment]
Nice - it seems like we're mostly in agreement and I see @jlebon changed the title of this issue to denote the change in scope. @jlebon as part of this we should probably be able to make "detecting if a config was provided to the machine (either fetched or embedded)" easier (https://github.com/coreos/ignition/issues/903) ?

**Comment by jlebon** [comment]
> @jlebon as part of this we should probably be able to make "detecting if a config was provided to the machine (either fetched or embedded)" easier (#903) ?

Yeah, I think you're right in that it simplifies the "only emit a message once" bit. Though I expect this issue will mostly be about moving code around, so I told @sohankunkerkar to keep working with what he has and we can rebase changes needed for this issue on top of his work.

**Comment by lucab** [comment]
This ticket got closed, so are we now guaranteeing that "Ignition fetches the configuration only once in the fetch stage"?

**Comment by bgilbert** [comment]
Yes, 88013e5f354d6497860b7a4fe57d56444c3913b9 changed the acquire logic to ensure that.

**Comment by arithx** [comment]
Sorry about that @lucab, in hindsight I should have updated the commit message for that commit to make it more obvious that it was now doing more than just always writing the cache config.

**Comment by LorbusChris** [comment]
this issue is referenced here: https://github.com/coreos/ignition/pull/958/files#diff-e3491b7c0e160811ce6761d5a1117558R95
ptal @sohankunkerkar
