### ISSUE TITLE
New release (2.2.2?) with support for specifying HTTP headers

### ISSUE THREAD

**Issue by MPV** [coreos/ignition#957]
# Feature Request #

It looks like 2.2.1 was made [just before that commit/merge was done](https://github.com/coreos/ignition/compare/v2.2.1...master). 😊 

## Environment ##

What hardware/cloud provider/hypervisor is being used to run Ignition? `OpenStack`

## Desired Feature ##

Would you be open to releasing a new version of Ignition containing the fix done in https://github.com/coreos/ignition/pull/892 ? ❤️ 

## Other Information ##

See https://github.com/openshift/okd/issues/127.

**Comment by LorbusChris** [comment]
Note to maintainers:
No need for stabilization of spec v3.1 should be necessary for this. Installer uses an ignition shim for OpenStack node provisioning and we could as well use spec v3.1.0-experimental for that until it has been stabilized.

**Comment by MPV** [comment]
I created this issue in an ambition/attempt to build my own FCOS image (with the fix from #892), but I haven't figured out yet [how to build my own FCOS image](https://github.com/coreos/fedora-coreos-tracker/issues/319). Not sure if I'll pursue that at this moment, might try again after some time (unless someone else here has succeeded before me).

Maybe I should also mention/clarify that this issue (no release yet of #892) is a blocker for using OKD 4.4 on OpenStack.

**Comment by bgilbert** [comment]
Ignition 2.3.0 is now released, with a stabilized spec 3.1.0.
