### ISSUE TITLE
Starting Docker on boot

### ISSUE THREAD

**Issue by korggy** [coreos/ignition#963]
What is the recommended way to create an Ignition file that configures CoreOS to start Docker on boot? I know there are some issues around starting Docker at the proper time so it doesn't hang other startup processes.

**Comment by lucab** [comment]
Unfortunately `CoreOS` is not enough to identify which distribution you are using, and how start to Docker is a distribution-specific question.

I'm closing this one as it isn't really a bug report, feel free to repost this question to the community forum of your distribution. To my knowledge, in most cases it is auto-started via a socket unit.
