### ISSUE TITLE
units: empty dropins are not written to disk

### ISSUE THREAD

**Issue by lucab** [coreos/ignition#975]
# Bug #

## Operating System Version ##

Current Fedora CoreOS stable, `31.20200407.3.0`

## Ignition Version ##

Ignition 2.2.1 (but applies to 0.x releases too).

## Reproduction Steps ##

Ignition config:

```json
{
  "ignition": {
    "version": "3.0.0"
  },
  "systemd": {
    "units": [
      {
        "name": "zincati.service",
        "dropins": [
          {
            "name": "empty.conf",
            "contents": ""
          }
        ]
      }
    ]
  }
}

```

On the provisioned machine:
```
$ sudo stat /etc/systemd/system/zincati.service.d/empty.conf
stat: cannot stat '/etc/systemd/system/zincati.service.d/empty.conf': No such file or directory
```

## Other Information ##

This came up as an higher-level templating system ([in MCO](https://github.com/openshift/machine-config-operator/commit/32eaf3912fe38837ccf6d38a61497dadda9a7741#diff-e11abccbe42778da5d2d198ed105015dR1)) ended up synthesizing an empty content.

Apparently we are explictly skipping dropins with an empty content, but I'm not sure why: https://github.com/coreos/ignition/blob/ee616d5fb3d21babe288877e842ea137f3e68d0d/internal/exec/stages/files/units.go#L186-L188

/cc @runcom @arithx @bgilbert

**Comment by LorbusChris** [comment]
This is supported by systemd and does the following, according to https://github.com/systemd/systemd/blob/6ae827906d3ba4f6eda2f6f27ff41d01b965f572/man/systemd.unit.xml#L205-L210

> If a unit file is empty (i.e. has the file size 0) or is symlinked to /dev/null, its configuration will not be loaded and it appears with a load state of "masked", and cannot be activated. Use this as an effective way to fully disable a unit, making it impossible to start it even manually.

**Comment by LorbusChris** [comment]
Maybe I misunderstood the intention here, but the above would be true for systemd unit files.

**Comment by LorbusChris** [comment]
Ok I definitely misunderstood. An empty drop-in file would just exist, but not override any setting from the unit. Is that correct?

**Comment by lucab** [comment]
@LorbusChris yes this is for empty dropins. They don't override service units wholly. However they do override lower-priority dropins with the same name.
While I've personally never seen this used in the wild, it's still a good point here.

**Comment by arithx** [comment]
> However they do override lower-priority dropins with the same filename.

I hadn't thought of that. My initial gut reaction was that this didn't really make much sense as it would be effectively the same as writing nothing at all.

ASIDE: if we do make a change we'll probably need to also backport it into `spec2x`.

----

Does anyone have context on why `Contents` is an optional field? The only two fields for dropins are `Name` & `Contents`, to me it feels like we should be requiring the specification of `Contents` (even if it's just an empty string).

**Comment by bh7cw** [comment]
I am interested and want to learn how to deal with it if it's possible.

**Comment by dustymabe** [comment]
Thanks @bh7cw !

**Comment by bgilbert** [comment]
> Does anyone have context on why Contents is an optional field?

My guess is "convention".  If the struct adds a third field, it should be possible to override only that field from a merged config.
