### ISSUE TITLE
AWS S3 Region Incorrectly Determined as us-east-1

### ISSUE THREAD

**Issue by karlglrak** [coreos/ignition#992]
# Bug #

## Operating System Version ##
CoreOS/Flatcar v2247.5.0 onwards

## Ignition Version ##
0.33.0 onwards (see diff below)

## Environment ##
Running on AWS **outside** of us-east-1.
VM running in a private subnet with access to S3 via an S3 endpoint w/ prefix-list https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-s3.html

## Expected Behavior ##
File fetched from S3 after correctly determining region

## Actual Behavior ##
IP resolved to us-east-1 - see below error:
> [  127.655946] ignition[446]: files: createFilesystemsFiles: createFiles: op(3): Error fetching file <<FILENAME>>: RequestError: send request failed
> 
> caused by: dial tcp 52.216.108.117:443: i/o timeoutM
> [K[[0;1;31mFAILED[0m] Failed to start [0;1;39mIgnition (files)[0m.

## Reproduction Steps ##
1. Create AWS VPC w/ s3 endpoint and subnet with route table using s3 endpoint prefix list in non us-east-1 region
2. Create server in subnet w/ ignition file sourced from S3

## Other Information ##
Was last working for us in CoreOS/Flatcar 2191.5.0, so the breaking change is in this diff https://github.com/coreos/ignition/compare/0c1da80127dcfcae86487929aea971a1442477d5...d5237546eb34eb78e338de88332010a4c3d13b5e#diff-3ff2bff2e87bc5cb1e48690c76e25740

Very likely this issue was introduced via #826

**Comment by hynd** [comment]
I think #933 should fix this

**Comment by arithx** [comment]
Should be fixed by #1078
